bin/mobile-center.js
package.json

Had several weird error reports from customers that were caused by insufficient node versions. This gives an explicit error and fails to run if they don't meet minimum version requirements.

Added check for current version of node to launch script

---

src/util/interaction/prompt.ts

Wasn't rejecting on exception, thus breaking the -q switch in all sorts
of weird ways.

Fixed bug in return of prompt.question.

---

src/commands/test/lib/appium-preparer.ts
src/commands/test/lib/calabash-preparer.ts
src/commands/test/lib/path-resolver.ts
src/commands/test/lib/test-manifest.ts
src/commands/test/lib/uitest-preparer.ts
src/commands/test/prepare/appium.ts
src/commands/test/prepare/calabash.ts
src/commands/test/prepare/uitest.ts
src/commands/test/run/appium.ts
src/commands/test/run/calabash.ts
src/commands/test/run/uitest.ts
src/util/misc/promisfied-glob.ts
test/commands/test/lib/appium-preparer-test.ts

This PR unifies the following argument names for `prepare [framework]` and `run [framework]` commands:
`--project-dir` for argument that points to the source directory. The current name is `--workspace` for Calabash.
`--build-dir` for argument that points to the build directory. The current name is either `--build-dir` for Appium and Espresso, and `--assembly-dir` for Xamarin UI Tests.

Test cloud: making argument names consistent for all supported frameworks:

---

src/commands/test/lib/appium-preparer.ts
src/commands/test/lib/calabash-preparer.ts
src/commands/test/lib/espresso-preparer.ts
src/commands/test/lib/prepare-tests-command.ts
src/commands/test/lib/run-tests-command.ts
src/commands/test/lib/uitest-preparer.ts
src/commands/test/prepare/appium.ts
src/commands/test/prepare/calabash.ts
src/commands/test/prepare/espresso.ts
src/commands/test/prepare/uitest.ts
src/commands/test/run/appium.ts
src/commands/test/run/calabash.ts
src/commands/test/run/espresso.ts
src/commands/test/run/manifest.ts
src/commands/test/run/uitest.ts
src/util/misc/promisfied-fs.ts

All `prepare` commands share two command line arguments: 
1. `--include`. This allows user to add additional files to the Test Cloud upload.
2. `--test-parameter`. This allows user to add additional test parameters to the manifest.
In the current version, these parameters are passed to external `prepare` process (for frameworks that need it). That process parses them, copies to the artifacts directory, and saves appropriate information to the test manifest.
That has two problems:
1. We need to implement parsing and validation multiple times.
2. It is very easy to get inconsistent behavior. For example, the Calabash prepare command separates key / values by using colon (':'), while other frameworks use equal sign ('=').
This PR fixes that. Now the CLI itself is reponsible for processing …

Test cloud calabash

---

src/commands/test/category.txt
src/commands/test/check-state.ts
src/commands/test/lib/help-messages.ts
src/commands/test/lib/prepare-tests-command.ts
src/commands/test/lib/run-tests-command.ts
src/commands/test/prepare/appium.ts
src/commands/test/prepare/calabash.ts
src/commands/test/prepare/category.txt
src/commands/test/prepare/espresso.ts
src/commands/test/prepare/uitest.ts
src/commands/test/run/appium.ts
src/commands/test/run/calabash.ts
src/commands/test/run/category.txt
src/commands/test/run/espresso.ts
src/commands/test/run/manifest.ts
src/commands/test/run/uitest.ts

The biggest change in this PR is introducing new module "help-messages", which stores messages for all Test Cloud commands and arguments. This fixes two problems:
1. Some commands shared arguments names, but used separate help strings which could easy get out of sync.
2. It was very difficult to review help messages, which were scattered around the entire project.

Test Cloud: better commands and arguments help messages

---

src/commands/test/lib/appium-preparer.ts
src/commands/test/lib/espresso-preparer.ts
test/commands/test/lib/appium-preparer-test.ts

Very simple change.
Currently manifest file names for different frameworks are inconsistent. Calabash and UI Tests use `manifest.json`, and Espresso and Appium use `test-manifest.json`.
This change fixes that and uses `manifest.json` everywhere. This is important for build tasks, which will need predictable names.

Test Cloud: making manifest name consistent for all frameworks

---

src/commands/test/lib/included-files-parser.ts
src/commands/test/lib/prepare-tests-command.ts
src/commands/test/lib/run-tests-command.ts
src/commands/test/prepare/appium.ts
src/commands/test/prepare/calabash.ts
src/commands/test/prepare/espresso.ts
src/commands/test/prepare/uitest.ts
src/commands/test/run/appium.ts
src/commands/test/run/calabash.ts
src/commands/test/run/espresso.ts
src/commands/test/run/uitest.ts
test/commands/test/lib/included-files-parser-test.ts

In the current version, values of the `--include` argument had to use format `targetPath=sourcePath`.
This change allows to use only single path, as long as it is inside "root directory", i.e.:
- `--build-dir` for Xamarin UI Tests, Espresso and Appium
- `--project-dir` for Calabash
This change also improves validation and unit tests for included files parser.

Test Cloud: support for relative paths in --include argument

---

src/commands/test/prepare/calabash.ts
src/commands/test/prepare/uitest.ts
src/commands/test/run/calabash.ts
src/commands/test/run/uitest.ts

Last change before we are ready for VSTS tasks integration.
One of the previous changes replaced "--workspace" parameter for Calabash commands with "--project-dir". The new name follows the naming convention used elsewhere in the CLI.
However, the Test Beacon UI generates CLI command for submitting tests, and it still uses "--workspace". We cannot expect that the CLI and UI will be released at the same time (and that all users will immediately upgrade the CLI), so we want to keep the old parameter (along with the new one) for some time. The entire update will go as follows:
1. We will release the new CLI which accepts both --workspace and --project-dir
2. A week after that we will update instructions in our UI.
3. After a month or two, with a new CLI release, we will remove --workspace …

Test Cloud: adding back --workspace parameter to ensure backwards compatibility

---

src/util/commandline/category-command.ts
src/util/commandline/help.ts
src/util/interaction/out.ts

Fix for #93 
1. Fixed the explanation text formatting by setting the `colWidths` on the `noTableBorders` settings set. `colWidths` are calculated from the current console width.
2. Fixed another problem which also broke output formatting in some consoles (e.g. cmder and powershell). It was caused by the presence of the CRLF characters in some of the category.txt files. cli-table2 doesn't take CR into account (i.e. doesn't removes it when wrapping strings to fit into table cell), thus breaking the formatting.
Here is how it looks like after the fix (powershell console as an example):
Please, note that there is no space between rightmost top cell and the one below it (see the red line on the next image):
Is it by design? Or should I add a horizontal space between them?

Default explanation text for `mobile-center test` is poorly formatted

---

src/commands/test/generate/uitest.ts

- Perform the parameter validation in run as throwing an exception within the constructor results in no output.  This had also broken `help test generate uitest`.
- Compare `files.length` to 0 as `files.length` always evaluates to false.
- Missing return when using `failure()`
@krukow There will be a separate PR to fix the `help test prepare/run` commands

Fixes for `test generate uitest`

---

src/commands/lib/logout.ts
src/commands/login.ts
src/util/apis/create-client.ts
src/util/apis/mobile-center-client-credentials.ts
src/util/commandline/command.ts
src/util/profile/telemetry.ts

Wasn't properly handling the case where CLI thinks you're logged in but the credential isn't in the credential store/keychain. Result was "locked-up" spinner that never completed.
Fixed some unhandled promise rejection warnings.
Fixed some typos.

Fixing login issues with missing credentials.

---

src/commands/test/lib/prepare-tests-command.ts
src/commands/test/lib/run-tests-command.ts
src/commands/test/prepare/calabash.ts
src/commands/test/prepare/uitest.ts
src/commands/test/run/calabash.ts
src/commands/test/run/uitest.ts

Otherwise:
- nothing is output
- the help command is broken

Avoid throwing errors in command constructors

---

src/commands/apps/lib/format-app.ts

Talked about this with @elamalani a couple of weeks ago.
The ID is currently of no use to the user and might potentially cause confusion.

Remove apps' ID from console output

---

src/commands/crashes/category.txt
src/commands/crashes/lib/upload-symbols-error.ts
src/commands/crashes/upload-symbols.ts
src/util/misc/jszip-helper.ts
test/commands/crashes/upload-symbols/upload-symbols-test.ts

Implemented upload-symbols command in accordance to the specification - "-s", "-x" and "-m" switches are supported.
Command execution example: 
Help:
Comments and suggestions are welcome!

Add upload-symbols command for Crashes

---

src/commands/test/lib/help-messages.ts
src/commands/test/lib/run-tests-command.ts
src/commands/test/lib/test-cloud-uploader.ts
src/util/apis/generated/models/index.d.ts
src/util/apis/generated/models/testCloudStartTestRunOptions.js
src/util/apis/generated/operations/index.d.ts
src/util/apis/generated/operations/test.js
swagger/bifrost.swagger.json

Add `--language` parameter to `test run`

---

src/commands/test/lib/run-tests-command.ts
src/commands/test/run/manifest.ts

App path is required for all commands except `manifest`, not only by `manifest`

Fix app path (not) required

---

src/commands/test/lib/calabash-preparer.ts
src/commands/test/lib/run-tests-command.ts
src/commands/test/prepare/calabash.ts
src/util/misc/process-helper.ts

Fixes a regression introduced with a recent fix for test parameters.
With the latest fix, we pass empty test parameters array to the `CalabashPreparer` if no parameters are used. However, the preparer was not handling it correctly, and generated empty `--test-parameters` argument passed to the Ruby CLI `test-cloud`. The Ruby CLI couldn't parse it, and returned a failure.

CalabashPrepare: fixing regression when no test parameters are provided

---

src/util/apis/user-agent-filter.ts

Recently I have noticed that 'upload-symbols' tests are crashing.
I have found that tests themselves are OK, and Nock is a source of crashes.
The exception contains the following message: 
`"Failed to convert header keys to lower case due to field name conflict: user-agent"`
It is thrown in the node_modules\nock\lib\common.js, when Nock tries to normalize the incoming headers by lowercasing their names:
``` //  For each key in the headers, delete its value and reinsert it with lower-case key.
//  Keys represent headers field names.
var lowerCaseHeaders = {};
_.forOwn(headers, function(fieldVal, fieldName) {
var lowerCaseFieldName = fieldName.toLowerCase();
if(!_.isUndefined(lowerCaseHeaders[lowerCaseFieldName])) {
throw new Error('Failed to convert header keys to lower case due to field …
```

Fixed Nock-dependent tests

---

scripts/autorest.js
src/commands/build/branches/lib/format-build.ts
src/commands/build/branches/list.ts
src/commands/build/branches/show.ts
src/util/apis/generated/operations/buildOperations.js
swagger/bifrost.swagger.json

Implemented 'build branches list' command:
Refactored 'build branches show' to extract common output logic.
Depends on #135 for 'build branches show' implementation

Implemented 'build branches list' command

---

gulpfile.js
package.json
scripts/autorest.js

You can now do:
```
gulp autorest --env <dev|int>
```
or
```
npm run autorest -- --env <dev|int>
```
to download and regenerate the client in one shot.
Added fixups to work around autorest issue https://github.com/Azure/autorest/issues/2008.
Broke out individual parts of codegen into separate gulp tasks so you can generate without downloading for example.

Download swagger automatically & new swagger fixups

---

src/commands/build/branches/lib/format-build.ts
src/commands/build/branches/list.ts
src/commands/build/branches/show.ts
src/commands/build/download.ts
src/commands/build/logs.ts
src/commands/build/queue.ts
src/util/commandline/option-parser.ts

This PR fixes the problem described in [the task](https://mseng.visualstudio.com/Mobile%20Center/Command%20Line%20Interface/_workitems?id=951461&_a=edit). It is not specific for the "build" commands and occurs for any command having required arguments (e.g. "apps create").

"-v" switch works correctly when used with a command having required arguments

---

src/commands/distribute/groups/download.ts

Implemented 'distribute groups download' command

---

src/commands/distribute/releases/delete.ts

Implemented 'distribute releases delete' command

---

src/commands/build/download.ts
src/commands/distribute/groups/create.ts
src/commands/distribute/groups/download.ts
src/commands/distribute/groups/lib/group-view-helper.ts
src/commands/distribute/groups/show.ts
src/commands/distribute/groups/update.ts
src/commands/distribute/release.ts
src/util/commandline/command-runner.ts
test/commands/distribute/release/release-test.ts

Moved CommandFailedResult exceptions handling to the command-runner.ts and fixed test which was not handling the promise rejection before this change

Moved CommandFailedResult exceptions handling to the command-runner.ts

---

bin/mobile-center.js
src/commands/test/lib/calabash-preparer.ts
src/commands/test/lib/exit-codes.ts
src/commands/test/lib/help-messages.ts
src/commands/test/lib/run-tests-command.ts
src/commands/test/lib/state-checker.ts
src/commands/test/lib/uitest-preparer.ts
src/commands/test/lib/xcuitest-preparer.ts
src/commands/test/run/xcuitest.ts
src/commands/test/status.ts
src/index.ts
src/util/misc/ios-bundle-archiver.ts

This PR contains two changes:
1. It adds `timeout` argument to all Test Cloud `run` commands. That will allow us to limit the time that we spend waiting for test completion, and is needed for Build - Test integration.
2. Improves messages. 
Many of our users complaint that the message "please inspect logs for more details" is confusing - there are no logs. This message is now removed; instead, the code prints exit code, what can be helpful during automation.
```
...
Current test status: Validating
Current test status: Validation completed. Waiting for devices
After 30 seconds, command timed out waiting for tests to finish.
Command failed: cannot run Test Cloud tests. Returning exit code 64.
```

Test Cloud commands: adding timeout and fixing "please inspect logs" messages

---

src/commands/test/lib/interaction.ts
src/commands/test/lib/uitest-preparer.ts

The Mobile Center CLI calls `test-cloud.exe` (directly or using Mono on Mac) to prepare UI Tests, and prints its messages to console output. We want to make that invisible to user, but right now the `test-cloud.exe` prints its own name in a few error messages.
This change finds lines with `test-cloud.exe` and removes them from Mobile Center CLI output.
Link to the bug: https://msmobilecenter.visualstudio.com/Test/_workitems?id=4122&_a=edit

Fixes bug 4122: Remove `test-cloud.exe help {command}` from error messages

---

src/commands/build/download.ts
src/util/misc/jszip-helper.ts
src/util/misc/promisfied-fs.ts

Unsigned iOS builds result in .xcarchive instead of .ipa now. I have added .xcarchive support to 'build download' command. The .xcarchive folder is renamed to follow the common name convention.

Implemented .xcarchive support for 'build download' command

---

bin/mobile-center.js
gulpfile.js
package.json
scripts/autocomplete-tree.js
src/commands/setup-autocomplete.ts
src/util/commandline/autocomplete.ts
src/util/commandline/index.ts

Implemented auto-completion for categories, commands and options using [Omelette](https://www.npmjs.com/package/omelette).
Auto-completion script can be installed using "setup-autocomplete" command. Bash, zsh and fish shells are supported.
Terminal should be restarted afterwards for the changes to take effect.

Implemented auto-completion support for categories, commands and options

---

src/commands/test/run/xcuitest.ts

When uploading xcuitests the app dir is matched with: ^*[^-Runner].app$
[^ does not work the way the author intended with the result of any app with R,u,n,e,r characters in their name will fail to be matched. (and . is problematic too) This change fixes the regexp.

fix regexp

---

src/commands/test/lib/uitest-preparer.ts

User ran:
```mobile-center test run uitest --app "owner/appname"
--devices "owner/device" --app-path "c:\path\with spaces\app.apk"
--test-series "master" --locale "en_US" --build-dir
"C:\Users\users\documents\visual studio 2015\projects\etc"
```
And got:
```
Preparing tests... 'C:\Users\user\documents\visual' is not recognized
as an internal or external command, operable program or batch file.
```
Code was missing an extra layer of quotes in path if there's a space
before shelling out to the test preparer command.

Fix for customer reported error when spaces in --build-dir.

---

src/commands/analytics/app-versions.ts
src/commands/analytics/audience.ts
src/commands/analytics/events/show.ts
src/commands/analytics/lib/analytics-constants.ts
src/commands/analytics/sessions.ts

Updated help messages of "analytics" commands with the time range parameters to contain default values of these parameters
Fix for #199

Updated help messages for time range parameters

---

src/commands/setup-autocomplete.ts

Added hint to restart shell after "setup-autocomplete" is executed
Clarified what is default value for "--shell" parameter in help message

Small "setup-autocomplete" command improvements

---

src/commands/analytics/audience.ts
src/commands/analytics/events/show.ts
src/commands/analytics/sessions.ts
src/util/interaction/out.ts

Fixed issue with extra commas in CSV output of "analytics" commands when some of the data tables are omitted.
Fixed #201 and #203

Fixed issue with extra commas in CSV output of "analytics" commands

---

src/commands/login.ts

"Created from mobile center cli" has some typos (product name isn't capitalized, nor is acronym 'CLI').

Cleaner API token description

---

src/commands/login.ts
src/util/commandline/command.ts
src/util/profile/environment-vars.ts
src/util/profile/index.ts

The app now checks if MOBILE_CENTER_ACCESS_TOKEN environment variable is set. If it is set, it's value will be used as token. MOBILE_CENTER_ENV environment variable may be optionally set to specify environment ("prod" by default). Please note that "mobile-center login" command is not allowed when MOBILE_CENTER_ACCESS_TOKEN is set.

Access token and environment name can now be set with environment vars

---

src/commands/lib/logout.ts
src/commands/logout.ts

Updated "logout" command to make sure that the app doesn't always waits for 10 seconds before exiting

Progress spinner is now shown during the whole logout process

---

src/commands/build/branches/list.ts
src/commands/build/branches/show.ts
src/commands/build/download.ts
src/commands/build/logs.ts
src/commands/build/queue.ts

"build branches list", "build branches show", "build queue" commands show clear error message now when app is not configured for building;
"build logs", "build download" commands show "not found" error message instead (as API returns HTTP 404 when app is not configured for building);

Clear error messages for "build" commands when they are run for app not configured for building

---

src/commands/test/lib/help-messages.ts
src/commands/test/stop.ts

The added command has been implemented in order to support Jenkins Plugin for Mobile Center Test.
Also, users will be able to cancel the testing process from the command line when they want.

Add 'mobile-center test stop' command for stopping the started test run.

---

src/commands/codepush/deployment/list.ts

All naming of codepush in the code should use `CodePush`.

[Typo fix] codepush deployment list naming

---

src/commands/codepush/deployment/add.ts

This PR attempts to integrate `codepush deployment add` command into the mobile center as `mobile-center codepush deployment add`.

codepush-deployment-add

---

package.json
src/commands/codepush/patch.ts

This PR migrates `codepush patch` into mobile center:
The original codepush patch command [illustration](https://github.com/Microsoft/code-push/tree/master/cli#patching-update-metadata).
The current version:

code-push-patch

---

src/commands/orgs/lib/org-users-helper.ts
src/commands/orgs/list.ts
src/commands/test/lib/calabash-preparer.ts
src/commands/test/lib/espresso-preparer.ts
src/commands/test/lib/help-messages.ts
src/commands/test/lib/run-tests-command.ts
src/commands/test/lib/state-checker.ts
src/commands/test/lib/test-cloud-uploader.ts
src/commands/test/lib/uitest-preparer.ts
src/commands/test/run/uitest.ts
src/util/misc/ios-bundle-archiver.ts
src/util/portal/portal-helper.ts
test/util/misc/ios-bundle-archiver-test.ts

There is a discrepancy between the parameters available when uploading tests via `test-cloud.exe` and those uploaded by `mobile-center-cli`.
This PR adresses that by introducing the ability to add those parameters to the uitest command.
Also including minor bug fixes with this PR that were bundled up in the assigned work.
This PR won't start functioning until UITest has implemented [this PR](https://github.com/xamarin/Xamarin.UITest/pull/1192) - after which I advise we update the minimum version on UITest within the mobile-center-cli.
This work is part of this [VSTS Ticket](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/22164).
And along with the UITest changes resolves [this github issue](https://github.com/Microsoft/mobile-center-cli/issues/237).
- [Test upload …

Test cloud feature complete plus minor bug fixes

---

src/commands/test/lib/uitest-preparer.ts

The upgrade to UITest 2.2.0 was triggering an issue present in the version check logic.
If the major or minor version is greater than the minimum (rather than equal) then the current version is higher.

UITest: Fix incorrect logic on test-cloud.exe version check

---

src/commands/codepush/lib/cordova-utils.ts
src/commands/codepush/lib/file-utils.ts
src/commands/codepush/lib/hash-utils.ts
src/commands/codepush/lib/react-native-utils.ts
src/commands/codepush/lib/update-contents-tasks/sign.ts
src/commands/codepush/lib/update-contents-tasks/zip.ts
src/commands/codepush/release-cordova.ts
src/commands/codepush/release-react.ts

1. add missed `hasArg`s
2. add `projectRoot?` prop for `getCordovaProjectAppVersion` and `getReactNativeProjectAppVersion` methods
3. make all method in `file-utils.ts` synchronous
4. add platform validation both for React and Cordova
5. other small fixes and improvements

additional improvements for "codepush release" related commands

---

src/commands/codepush/patch.ts
src/commands/codepush/promote.ts

In the standalone CodePush CLI, when performing CodePush Patch, users only need to specify deployment name without release label as mandatory parameter.
Also fixed issue with required args for promote command

Fixed issues with CodePush commands

---

src/util/apis/create-client.ts

Without this change appcenter cli crashes on case sensitive filesyetems with:
```
kamstrup@mandrill:~$ appcenter 
module.js:538
throw err;
^
Error: Cannot find module './generated/AppCenterClient'
at Function.Module._resolveFilename (module.js:536:15)
at Function.Module._load (module.js:466:25)
at Module.require (module.js:579:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/usr/lib/node_modules/appcenter-cli/dist/util/apis/create-client.js:6:25)
at Module._compile (module.js:635:30)
at Object.Module._extensions..js (module.js:646:10)
at Module.load (module.js:554:32)
at tryModuleLoad (module.js:497:12)
at Function.Module._load (module.js:489:3)
```

Fix generated/appCenterClient filename casing

---

src/commands/test/lib/run-tests-command.ts

When there is not profile present and an error happens, the true error is masked by an error trying to read the user's profile. 
For example in version 1.0.2 you have
```bash
➜  ~ appcenter test run uitest --app "user/app" --devices 9c3473a9 --app-path CreditCardValidator.iOS.ipa --test-series "master" --locale "en_US" --build-dir bin/Release --uitest-tools-dir /non-existant  --token 234
Preparing tests... failed.
Error: Command 'test run uitest --app user/app --devices 9c3473a9 --app-path CreditCardValidator.iOS.ipa --test-series master --locale en_US --build-dir bin/Release --uitest-tools-dir /non-existant --token 234' failed with exception "Cannot read property 'email' of null"
```
with this change:
```bash
node dist/index.js test run uitest --app "user/app" --devices 9c3473a9 …
```

Guard against non-existing profile: fix failed with exception "Cannot read property 'email' of null"

---

src/commands/test/lib/run-tests-command.ts
src/commands/test/lib/uitest-preparer.ts

Users have been sending just the environment message, so to help support we should explicitly ask for both the environment message and the error message before hand.
- Slight alteration to blanket error message to ask for both env message and error message.
- Better messages for test-cloud.exe error codes.

Test cloud error message improvements

---

src/commands/codepush/lib/update-contents-tasks/zip.ts
src/commands/codepush/release-react.ts

Update/Release for Cordova has another structure than React updates:
1. Cordova update should contain www/ root folder inside the archive
2. React update should contain CodePush/ root folder inside the archive

[codepush] fix for cordova-release command

---

src/commands/codepush/lib/legacy-codepush-service-client.ts
src/commands/codepush/lib/release-command-skeleton.ts
src/commands/codepush/lib/release-strategy/appcenter-release.ts
src/commands/codepush/lib/release-strategy/legacy-service-release.ts

This PR fixes the issue from the previous PR #321 that @christav pointed out.
This PR fixed:
1. private constructor properties mentioned in [here](https://github.com/Microsoft/appcenter-cli/pull/321#discussion_r153288656). 
2. remove debug function to pass through [here](https://github.com/Microsoft/appcenter-cli/pull/321#discussion_r153288656).
@christav for the comment to not passing DefaultApp. Since codepush release command points to legacy one instead of the new one, this requirement makes us to think to pass the DefaultApp from higher level command to the lower level skeleton code. In other word, we do the code injection in purpose.  @max-mironov this is what I think from your written code.

[CodePush] fixed the debug function passing and private properties code

---

src/commands/codepush/lib/react-native-utils.ts
src/commands/codepush/lib/release-command-skeleton.ts
src/commands/codepush/lib/validation-utils.ts
src/commands/codepush/patch.ts
src/commands/codepush/promote.ts
src/commands/codepush/release-cordova.ts
src/commands/codepush/release-react.ts
test/commands/codepush/lib/validation-utils-test.ts

Currently, I can't specify `--target-binary-version` using semver range.
```
$ appcenter codepush release-react -a MyOrg/MyApp --deployment-name Staging --target-binary-version '1.2.x'
Error: Invalid binary version(s) for a release.
```
The document says strings `1.2.x` should be allowed.
https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli#target-binary-version-parameter
If the version is like `1.2.0`, it runs successfully.
I figured out the cause of the error and fixed it.
It's because of the usage of `semver` npm package.
```js
var semver = require('semver');
console.dir(semver.valid('1.2.0'));
// => '1.2.0
console.dir(semver.valid('1.2.x'));
// => null
console.dir(semver.validRange('1.2.0'));
// => '1.2.0
console.dir(semver.validRange('1.2.x'));
// => '>=1.2.0 <1.3.0' …
```

Fix validation of `--target-binary-version`

---

package-lock.json
src/util/profile/environments.ts

Upon attempting to submit an upload to a local instance of Asgard/Bifrost/XTC, I discovered that we get a fatal error that `portalBaseUrl` is `nil`.  Investigation and experimentation led me to realize that this `portalEndpoint` value needs to be set in order for login to succeed locally.
I left `loginEndpoint` as `null` because it appears that, when specified, `appcenter-cli` requires interactive login which is not an ideal workflow for our dev environment.

Provide portal endpoint for testCloudLocalDev env config

---

src/util/commandline/command.ts
src/util/commandline/help.ts
src/util/commandline/option-decorators.ts
src/util/commandline/option-parser.ts
test/util/commandline/option-decorators-test.ts

adding `common` property decorator to switch options and use it to disable better example and options

---

src/commands/codepush/release-cordova.ts

Since cordova-android ver7 assets directory location was changed. This PR fixes release-cordova command to use correct assets directory for release.
PR was tested for backward compatibility with previous cordova versions.
Related PR: https://github.com/Microsoft/code-push/pull/548

[CodePush][Cordova] Update assets manifest file location for release-cordova command

---

src/commands/test/lib/run-tests-command.ts
src/commands/test/prepare/uitest.ts
src/util/commandline/command.ts

We added the missing parameters to the main `run uitest` method and this makes the equivalent changes when the user calls `prepare` followed by `run manifest`.
We need this to support `--include-category` and `--exclude-category` in the VSTS Task among other client requests.
I moved `fixArrayParameter` out to the shared `Command` but please let me know if you'd rather see this moved out somewhere else.

UITest: adds ability to specify extra parameters to prepare uitest

---

src/commands/codepush/lib/react-native-utils.ts

My appcenter-cli version is 1.0.6. When I run this command for release my React Native Windows app:
```appcenter codepush release-react -a myh/thcs-uwp```
, I got this error message:
```
Detecting windows app version:
Running "react-native bundle" command:
node node_modules\react-native\local-cli\cli.js bundle --assets-dest C:\Users\myh\AppData\Local\Temp\code-push1171128-20424-1lwnbgu.lp5o --bundle-output C:\Users\myh\AppData\Local\Temp\code-push1171128-20424-1lwnbgu.lp5o\index.windows.bundle --dev false --entry-file index.windows.js --platform windows
Scanning folders for symlinks in D:\git\thcs\node_modules (31ms)
Scanning folders for symlinks in D:\git\thcs\node_modules (31ms)
Loading dependency graph, done.
bundle: start
bundle: finish
bundle: Writing bundle output to: …
```

Fix a bug where getReactNativeProjectAppVersion returns undefined

---

src/commands/build/branches/show.ts

This is because `buildNumber` can have different formats. It can be similar to build id, but can also be timestamp. If a user switches the format, then sort by `buildNumber` to get the latest build becomes unreliable

Sort builds by id instead of buildNumber

---

src/commands/codepush/lib/legacy-codepush-service-client.ts
src/commands/codepush/lib/release-command-skeleton.ts
src/commands/codepush/promote.ts

1. implement support for `disable-duplicate-release-error` flag.
2. rename `no-duplicate-release-error` flag to the `disable-duplicate-release-error` because of this issue https://github.com/substack/minimist/issues/123
3. remove `@shortName("d")` for `description` in `promote` command due to conflict with `destination-deployment-name` argument
4. rename `dest-deployment-name` to `destination-deployment-name` - avoid of using abbrivations

[CodePush] fix for --no-duplicate-release-error flag

---

package.json
scripts/autorest.js
scripts/download-swagger.js
scripts/fixup-swagger.js

The --env switch wasn't being properly passed to all the stages of the autorest command.

Update npm scripts to do autorest for non prod environments correctly

---

src/commands/test/lib/calabash-preparer.ts
src/commands/test/lib/prepare-tests-command.ts
src/commands/test/lib/run-tests-command.ts

*PR Updated after discovering some technical debt.*
Test parameters are passed incorrectly when preparing calabash tests.
`--test-parameter "a=b"` is passed as `--test-params` but it should be passed as `--test-parameters` as you can see from the `xamarin-test-cloud` gem:
```
test-cloud help prepare
...
-params, [--test-parameters=key:value]               # Example: -params username:nat@xamarin.com password:xamarin)
...
```
Also they are formatted incorrectly.
This PR fixes the problems.
With this change, they are passed as
```
test-cloud prepare XTCAndroidSample.apk \
--artifacts-dir /var/folders/hs/ycgt048163132zqg0mh_1r1h0000gn/T/appcenter-upload11814-29672-gm1jvu.bp70h \
--workspace "." \
--test-parameters "pipeline:calabash-android-in-container" "isolated:true"
```
In addition, this …

Use correct format for calabash test params

---

test/commands/test/lib/appium-preparer-test.ts

Typo in test caused false positive on test failure. With this change:  129 passing (674ms).

Fix incorrect test due to typo

---

src/commands/distribute/release.ts

When user distributes a release through CLI, the release version number is not shown properly. This PR fixed this issue: 
Above image shows the difference before and after the change.

Distribution release release version undefined

---

src/commands/lib/logout.ts
src/util/token-store/osx/osx-token-store.ts
test/util/token-store/osx-keychain-parser-test.ts

Previously, `OsxTokenStore` saved `"null"` as a string when `tokenId` was missing after login (which expectedly happens when using the interactive login flow). `"null"` is truthy so the code path for dealing with missing token IDs during logout was never entered.
This PR fixes both saving of tokens  for the future and adds backwards compatibility for existing, "broken" tokens in users' keychains.

Fix token deletion on logout

---

src/commands/test/lib/run-tests-command.ts

> Preparing tests... done.
Validating arguments... done.
Creating new test run... done.
Validating application file... done.
Uploading files... done.
Starting test run... done.
Error: Cannot read property 'vstsIdVariable' of undefined
It happens for any test run because of incorrect context.

Fix the error Cannot read property 'vstsIdVariable' of undefined

---

src/commands/test/lib/run-tests-command.ts

We've observed errors like:
```
Error: EPERM: operation not permitted, unlink 'C:\BuildAgent\temp\buildTmp\appcenter-upload118115-6800-1ohlguf.j77hk\AndroidTestServer.apk'
```
particularly on Windows. 
This should not cause the CLI to exit, but rather it should issue a warning.

Windows EPERM: Warn and don't bail on failed cleanup

---

src/commands/codepush/lib/environment.ts
src/commands/codepush/lib/release-command-skeleton.ts
src/util/profile/profile.ts

`appcenter codepush release-react` fails with an error in a case:
```
Releasing update contents to CodePush:
Error: TypeError: Cannot read property 'environment' of null
```
1. Make sure that `appcenter-cli` is logged out
1. Run `appcenter codepush release-react` with `--token` and without `--env`
This is because `getUser()` does not always return a `Profile`.
It returns `null` when there is no `profile.json` in `~/.appcenter-cli` (see the line 145):
https://github.com/Microsoft/appcenter-cli/blob/d93908f5ed9e8523e020473f23b63c8c437beb2b/src/util/profile/profile.ts#L140-L161
In that case, `getUser().environement` throws the error:
https://github.com/Microsoft/appcenter-cli/blob/d93908f5ed9e8523e020473f23b63c8c437beb2b/src/commands/codepush/lib/release-command-skeleton.ts#L106
I added …

Fix the logic to get server URL

---

src/util/misc/promisfied-fs.ts

My PR fixes all cases which marked as `Doesn't work`
```
"args": [
// Add your Mobile Center CLI command
"test",
"run",
"uitest",
"--devices", "%deviceId%",
"--build-dir", "%pathToBuildDir%",
"--app-path", "%pathToApk%",
"--app", "%app%",
"--include", "config.json", // Works
"--include", "something/config.json", // Doesn't work
"--include", "1/2/3/4/5/config.json", // Doesn't work
"--include", "1/2/3/4/5/6" // Doesn't work
]
```

Create long path if it doesn't exist

---

src/commands/test/lib/run-tests-command.ts

Print an useful error message instead of an empty one.
For some reason server side returns the empty error message. It has been replaced by a general message which says "Could not start your tests. Maybe your subscription has expired."

Add error message if server message is empty

---

src/util/token-store/file/file-token-store.ts
test/util/token-store/file-store-test.ts

Cases exist where file token store doesn't have a directory to write to, so try and create it before accessing.

Make sure file token directory exists always.

---

src/commands/test/download.ts

I didn't check my last commit. Lesson learnt, we need CI and I need to be more careful 🙂

Fixes JSLint error with unused os import

---

src/commands/codepush/release-cordova.ts

When you run `appcenter codepush release-cordova` before you have run `cordova platform add` the wrong output folder is detected under `android`. This pull request moves the detection after the `cordova build` command. In newer versions of the `cordova-cli` the missing platform is automatically added, so a manuell execution of `cordova platform add` is not needed.
I also improved the `getOutputFolder` function in that way that when no output folder at all could be detected an error is presented to the user.

Wrong android output directory detection fixed

---

package-lock.json
package.json

Same as https://github.com/Microsoft/appcenter-cli/pull/325
If they are in `dependencies`, it enforces packages depends on `appcenter-cli` to install the same packages (@types/unzip, @types/xmldom and their dependencies).
So please add them as `devDependencies.`

Make @types packages dev dependencies

---

src/commands/test/lib/run-tests-command.ts

Since `testRun` gets passed to two `this.streamingOuput.text()` calls the same data is output twice when using `--output`.

Avoid duplicate output when using --async with --output

---

src/commands/test/lib/help-messages.ts
src/commands/test/lib/run-tests-command.ts
src/commands/test/lib/test-cloud-uploader.ts

We don't support showing symbolicated crashes.
The option `--dsym-dir` is deprecated and ignored.
The functionality with the ability to view and download raw (unsymbolicated) crash reports is available on appcenter.ms

Mark the option `--dsym-dir` as deprecated

---

src/commands/test/lib/uitest-preparer.ts

To allow the UITest CI to use the dev version of the test-cloud.exe file - we need to allow it in the CLI.
This small code change allows this (along with some changes in UITest itself).

Allow debug uitest console to be used when calling appcenter-cli

---

src/commands/test/lib/uitest-preparer.ts

Fixes incorrect parameter parsing when passing keystore details to test-cloud.exe.
Error before fix:
```
Invalid options were used to prepare the test artifacts, please try again. If you can't work out how to fix this issue, please contact support.
```

Parameters badly formatted when keystore used

---

src/commands/codepush/patch.ts
src/commands/codepush/promote.ts

I've added missing long arguments versions (-x, -m) for codepush patch/remove. Every argument out there has a long version, except in this case.
I've copied the values from CodePushReleaseCommandSkeleton.

Adds --mandatory and --disabled long arguments to codepush patch,remove

---

src/commands/apps/set-current.ts

I'm parsing help description and searching for upper casing of description's first char. All descriptions start with upper cased character except for one, which is fixed in this PR.

Fixes help description casing

---

src/commands/test/lib/test-cloud-uploader.ts

**Desciption:**
if we make a typo in an app name we get an empty error message:
```Preparing tests... done.
Validating arguments... done.
Creating new test run... failed.
Error:
```
This PR fixes that problem. We'll see the message
`The app name was not found for the provided org name`

Adds a useful error message

---

src/commands/codepush/lib/react-native-utils.ts
src/commands/codepush/release-react.ts
src/util/commandline/option-decorators.ts
src/util/commandline/option-parser.ts

Added `extra-bundler-option` option to `codepush release-react`. This can be used to pass custom arguments to bundler.
My own use case: specify `--extra-bundler-option='--max-workers=1'` to limit bundler's memory use.

CodePush: Add an option to pass extra react-native bundler options

---

src/commands/test/lib/prepare-tests-command.ts
src/commands/test/prepare/xcuitest.ts

**Problem:**
Valid prepare xcuitest command
`appcenter test prepare xcuitest --artifacts-dir AppCenterTest --build-dir DerivedData/Build/Products/Debug-iphoneos --debug` triggers error from CLI: `Error: This method must be overriden in derived classes`
**Changes:**
Added missing method.

Bug: appcenter-cli: Investigate reports that test-run-prepare prepare function is being called

---

src/commands/test/lib/appium-preparer.ts
src/commands/test/lib/calabash-preparer.ts
src/commands/test/lib/espresso-preparer.ts
src/commands/test/lib/help-messages.ts
src/commands/test/lib/uitest-preparer.ts
src/commands/test/lib/xcuitest-preparer.ts
src/commands/test/prepare/espresso.ts
src/commands/test/prepare/xcuitest.ts
src/commands/test/run/espresso.ts
src/commands/test/run/xcuitest.ts
test/commands/test/lib/espresso-preparer-test.ts
test/commands/test/lib/xcuitest-preparer-test.ts

**Problem:** `--include` argument is not supported for `Espresso` and `XCUITest`.
**Changes:**
- Added verification to raise an error when 'include' argument provided for Espresso and XCUITest.
- Unified error messages.
- Changed help messages for 'include' argument for Espresso and XCUITest.
- Added tests.
---
Error messages for Espresso/XCUITest:
```
Error: Argument --include cannot be used for Espresso
Error: Argument --include cannot be used for XCUITest
```
Help messages for Espresso/XCUITest/other:
```
--include <arg>           Attribute is not supported for Espresso
--include <arg>           Attribute is not supported for XCUITest
--include <arg>           Additional files and directories to include. The value must be either path relative to the input directory, or be in format …
```

Added verification to raise an error when 'include' argument provided for Espresso and XCUITest.

---

README.md
package-lock.json
package.json

- Adds verification error for `appcenter test run` on appium and xcuitest when --include parameter is used
- Updates launch tests to always use latest UITest version
- Fixes access token error on codepush command - [Issue 469](https://github.com/Microsoft/appcenter-cli/issues/469)
- Updates package npm dependencies

Release 1.1.2

---

src/commands/distribute/groups/update.ts
test/commands/distribute/groups/download-test.ts
test/commands/distribute/groups/update-test.ts

**Problem:**
AppCenter CLI have a problem with changing distribution group name:
`appcenter distribute groups update --group "Test" --app "v-anmits-mrwf/TestApp" --name "TestUpdated" --debug`
returns an error:
```
\ Validating parameters...Response status code: 404
Body: {"error":{"code":"NotFound","message":"Could not find distribution group with name TestUpdated"}}
Error: failed to check if the distribution group TestUpdated already exists
```
**Changes:**
- Fixed logic of detecting existing distribution groups.
- Added tests.
- Moved download test to correct folder.

Fixed logic of detecting existing distribution groups.

---

src/commands/codepush/lib/file-utils.ts
src/commands/codepush/lib/release-command-skeleton.ts
test/commands/codepush/codepush-release-test.ts
test/commands/codepush/lib/file-utils-test.ts
test/commands/codepush/utils.ts

**Issue**: We lose private key during release for RN from custom path because there should be root folder "CodePush" for React-Native app. (For Cordova it should be "www").  
**Suggestion fix**: In private key enabled case we should check that it is React-Native app and the last folder isn't "CodePush". In this case we should copy all contents to temp folder with root "CodePush" folder and then make release from here.

Fix release command with private key case

---

src/commands/test/generate/uitest.ts
src/commands/test/lib/generate-command.ts
test/commands/test/generate/uitest-test.ts

Improved error handling for generate uitest command:
- Moved code to copy templates to separate method.
- Added separate `catch` blocks for retrieving and replacing version.
- Added copying of original templates if replace operation failed.

Improved error handling for generate uitest command.

---

src/util/commandline/autocomplete.ts
test/util/commandline/autocomplete-test.ts
test/util/commandline/test-data/test-bash-profile

**Problem:** App Center CLI tab completion generates a `command not found` error on MacOS and some Linux environments in `Bash`. In `zsh` and `fish` everything looks good.
**Issues:** https://github.com/Microsoft/appcenter-cli/issues/285 https://github.com/Microsoft/appcenter-cli/issues/340
**Root-cause:**
App Center CLI tab completion depends on `bash_completion` which should be enabled in `bash_profile` before `appcenter completion`.
**Changes:**
- Implemented logic to enable bash_completion in bash_profile before appcenter completion. 
- Implemented test to verify autocomplete initialization.

App Center CLI tab completion generates a `command not found` error

---

package-lock.json
package.json

- Fixed logic of detecting existing distribution groups
- Improved error handling for generate uitest command
- Xamarin.UITest Android sign-info option fixed
- App Center CLI tab completion no longer generates a `command not found`

Release 1.1.4

---

.vscode/tasks.json

**Problem**: when I try to start debugging in VSCode with task `Launch with sourcemaps`(defined in `.vscode/launch.json`) I get error dialog with message `The preLaunchTask 'build-sourcemaps' terminated with exit code 1.` and the following output:
```
[17:50:46] Using gulpfile ~/Projects/appcenter-cli/gulpfile.js
[17:50:46] Starting 'build-sourcemaps'...
[17:50:46] Starting 'build-sourcemaps'...
[17:50:46] Starting 'build-ts-sourcemaps'...
[17:50:46] Starting 'copy-assets'...
[17:50:46] Starting 'copy-generated-client'...
[17:50:46] Starting 'build-ts-sourcemaps'...
[17:50:46] Starting 'copy-assets'...
[17:50:46] Starting 'copy-generated-client'...
[17:50:46] 'build-ts-sourcemaps' errored after 31 ms
[17:50:46] Error: gulp-typescript: A project cannot be used in two compilations at the …
```

Updated tasks.json to version 2.0.0

---

src/commands/codepush/release-react.ts

**Issue:** In case if user uses `--outputDir` option(custom directory for generating bundle) SourceMap will be generated in this `outputDir` directory even if user provide custom path for sourceMaps with `--sourcemap-output` option.
Note: SourceMaps is not generated in default case(without `--outputDir` and `--sourcemap-output` options)
**Solution:** SourceMap should be generated only if user provide some path for this in  `--sourcemap-output` option. 
Removed `if` block for forced generating sourceMaps.
Related issue: https://github.com/Microsoft/appcenter-cli/issues/504

Fix generating sourceMaps for react-native CodePush

---

src/commands/build/download.ts

This PR adds support for `AAR` packages for Android when downloading a build.

Add AAR as supported package extension

---

src/commands/build/download.ts

This PR adds a way of specifying the file name (by `--file` or `-f` option) for the `download` build command.
My use-case is that I need to download the build on a CI and I want to download it with the same file name every time.

Add option to specify the file name when downloading a build

---

src/commands/build/download.ts

As per https://github.com/Microsoft/appcenter-cli/pull/522#issuecomment-454747704, here's a small improvement on the help text for build download command.
Will look like this:
cc @owenniblock :)

Improve help text for build download command

---

src/util/token-store/win32/win-token-store.ts

https://github.com/Microsoft/appcenter-cli/issues/527
According to existing `win-credstore-parser` logic, `through2` should be used in `objectMode` on windows. Similar logic for osx looks correct.
@owenniblock please have a look at this PR. The current version is broken for windows, so new release required after merging this PR.

Fixed win-token-store logic.

---

package-lock.json
package.json
src/commands/crashes/lib/symbols-uploading-helper.ts
src/commands/crashes/upload-missing-symbols.ts
src/commands/crashes/upload-symbols.ts
test/commands/crashes/upload-symbols/upload-symbols-test.ts

This change adds support for uploading Breakpad symbols via the `crashes upload-symbols` command. Previously, all types of symbols were uploaded with the symbol_type attribute set to "Apple". 
Now, Breakpad symbols are able to be passed in using the `-b` flag.

Support breakpad symbol uploading

---

README.md
package-lock.json
package.json

- Updates launch test for App Center Build Appium upgrade
- Adds sourcemap-output-dir [for this issue](https://github.com/Microsoft/appcenter-cli/issues/538)
- Checks that `--app` arg is set in test wizard functionality
- Adds support for `release-electron` to code-push
- Adds support for beakpad symbol uploads

Release 1.1.12

---

src/commands/codepush/release-electron.ts

This change includes the following -
1. Updated the default Bundle-Name to 'index.electron.bundle' instead of platform specific names to align with the Electron CodePush SDK changes.
2. Removed the platform check for now as AppCenter does not support creating an Electron app yet.
3. Minor help test update

Update CodePush Electron command to align with Electron CodePush SDK

---

src/commands/distribute/release.ts
test/commands/distribute/release/release-test.ts

This PR updates the existing `appcenter distribute release` command to all our new, non-deprecated APIs to do its job.

Upgrade distribute api calls

---

README.md
src/commands/distribute/releases/edit.ts
test/commands/distribute/releases/edit-test.ts

This PR will add the `distribute releases edit` command which allows to enable or disable a release.
```
appcenter-cli (edit-release) » ./bin/appcenter.js distribute releases edit --help                                                                                                                            ~/work/microsoft/appcenter-cli
Enables or disables specified release
Usage: appcenter distribute releases edit -r|--release-id <arg> [-a|--app <arg>] <State>
Options:
-r|--release-id <arg>             Release ID
-a|--app <arg>                    Specify app in the <ownerName>/<appName> format
State                             Release state
```

Add `distribute releases edit` command

---

README.md
package-lock.json
package.json

- Upgrades API calls for distribute command to use non-depreciated calls
- Adds `distribute releases edit` command to enable and disable releases
- Displays all release destinations from `show` command
- Adds `distribute releases add-destination` command to allow users to add destinations to a release
- Makes CodePush Release Electron consistent with CodePush Release ReactNative by using the same switch for SourceMap as well as providing a new option for SourceMapOutputDir.
- Adds WebPack-CLI as Dependency, so it's packaged in the node_modules for use by CodePush Release Electron option

Release v1.1.14

---

src/commands/crashes/upload-missing-symbols.ts

At the moment, when sending a request to get the symbol groups for an app, we are sending a `top` parameter of the value `Number.MAX_SAFE_INTEGER`.
Unfortunately this number is 9007199254740991 - which is way larger than the value accepted by the backend data store used by the symbol indexing service.
I’ve changed it to use a 32 bit integer to fix this issue.

Fix getting symbol groups

---

src/commands/build/queue.ts

Whenever my company increments the version of our app, we trigger a build on AppCenter which works great. The issue this PR aims to solve is that once the build is complete, the notification we get in Slack does not include the version notes that are in the commit message. I've asked about getting this fixed on the AppCenter Intercom for a while now but was told that its unfortunately not a priority. Jihye did mention there is a temporary fix possible by manually making the API POST to AppCenter's API and including the `sourceVersion` argument  as seen here: https://openapi.appcenter.ms/#/build/builds_create
This works great so this PR adds the `sourceVersion` argument to the `build queue` command so it is possible as a workaround for now until AppCenter is able to pick up the commit …

Add source-version argument to the build queue command

---

package-lock.json
package.json

- Adds `--release-type` to `apps create` and `apps update` commands
- Adds `--source-version` argument to build queue command
- Fixes XML download process for UITest running against NUnit 3

Release 1.1.16

---

src/commands/apps/set-current.ts

Improves the error message when user tries to set the app and isn't using login.
I'm also creating an internal bug to change the environment variable `MOBILE_CENTER_CURRENT_APP` to `APP_CENTER_CURRENT_APP`.

Set Current is only compatible with `login` - tell users in help text

---

src/commands/codepush/lib/release-command-skeleton.ts
src/commands/codepush/lib/validation-utils.ts
test/commands/codepush/lib/validation-utils-test.ts

*Issue:* In case if a user specifies not full `--target-binary-version` like `1.0` or `1` then it will be treated as `1.0.X` and `1.X.X` on server side. It can confuse some users.
*Solution:* Added warning for this cases.
Screenshot:
Related issue: https://github.com/microsoft/code-push/issues/605

Add warning for poor target-binary-version in codepush

---

bin/appcenter.js
package.json

It's confusing when the `appcenter-cli` errors out with unhelpful parse errors. This will let users know that they need to use node 10.x in a more friendly way.
Output:
```
appcenter help
appcenter command requires at least node version 10.0.0.
You are currently running version v8.4.0.
Please upgrade your version of node.js to at least 10.0.0
```

Bumps the minimum node version to 10.x

---

package-lock.json
package.json

During the last release - I noticed that we're getting this warning if we remove `node_modules` and re install:
> npm WARN deprecated @types/promises-a-plus@0.0.27: Use '--lib es6' to get Promise types.
I've uninstalled that package and everything seems to work correctly.

Removes @types/promises-a-plus and regenerates on latest modules

---

package-lock.json
package.json

- Rolls back to 1.1.20 code to give users continued support for older node versions on this major version. Node 10.x work will be rereleased under appcenter-cli@2.0.0.

Release 1.2.2

---

src/commands/distribute/release.ts
src/util/apis/generated/models/index.d.ts
src/util/apis/generated/models/releaseUploadBeginRequest.js
src/util/apis/generated/operations/index.d.ts
src/util/apis/generated/operations/releaseUploads.js
swagger/bifrost.swagger.before.json
swagger/bifrost.swagger.json

**Why:** we need to support distribution of WinForms/WPF apps from .msi and .zip files
**What/How:** 
1. added `--build-version` extra parameter to `distribute release` command 
2. updated swagger (only build_version change and not the whole description from bifrost)
3. generated autorest models
4. passed the buildVersion to `release_uploads` endpoint call

Added build_version optional parameter to CLI release command

---

src/commands/codepush/lib/react-native-utils.ts
src/commands/codepush/release-react.ts

This is a respond PR to the request in React Native Code Push repository:
https://github.com/microsoft/react-native-code-push/issues/1626
This will enable CodePush to support the latest JS to Byte Code engine, the Hermes from Facebook to boost up Android's performance.
It will check if Hermes is enabled in the `android/app/build.gradle`, and invoke Hermes to compile the JS bundle to a byte code bundle, replace the original JS bundle with the newly created byte code bundle, and finally, upload the byte code bundle to App Center.
For a further explanation, a Hermes enabled Android build is capable to execute both JS and Hermes byte code bundle, hence we don't have to modify any code in the client side(react-native-code-push).
Screenshot:

Add Hermes support to React Native Code Push CLI

---

src/commands/codepush/lib/react-native-utils.ts

If hermes-engine is installed in node_modules, prefer the hermes binary
from there vs the one in hermesvm.
Ideally the `hermesCommand` could be parsed and used from the build.gradle
but parsing the gradle-to-js output for `hermesCommand` is not trivial. I think the
heuristic of preferring `hermes-engine` over `hermesvm` should be correct in the
vast majority of cases.
I've tested this locally with `ts-node` on a react-native 0.60.x project for the case when both `hermes-engine` and `hermesvm` are installed and when only `hermesvm` is installed.
Closes #653

Prefer hermes-engine over hermesvm

---

src/commands/distribute/release.ts
test/commands/distribute/release/release-test.ts

When distributing a release, it is now possible to choose not to notify testers.
Closes #602

Expose an option to avoid notifying testers of new releases

---

src/commands/distribute/groups/publish.ts
src/commands/distribute/stores/publish.ts
test/commands/distribute/fakes.ts
test/commands/distribute/groups/publish-test.ts
test/commands/distribute/stores/publish-test.ts

Add two new commands:
- `distribute stores publish` which performs the same actions as `distribute release --store`.
- `distribute groups publish` which performs the same actions as `distribute release --group`.

Add aliases for publishing to stores and groups

---

.gitignore
.npmignore
package.json

`npm pack` can be used to generate a smaller package, that we can then publish on GitHub. The rules in this PR select only the files in `bin/` and `dist/` for installation.

Fix "npm pack" usage

---

src/commands/distribute/release.ts
test/commands/distribute/release/release-test.ts

When running publishing a release to an Apple store track using `distribute release --store` or `distribute stores publish` with neither `-r` nor `-R` specified, an early failure warns of the required release notes. Release notes are not required for publishing to other types of stores.

Require release notes for store publishing to an Apple store track

---

src/commands/distribute/release.ts
test/commands/distribute/release/release-test.ts

This should fail early without creating a release on App Center
for the most common cases, and the least likely to change on
App Center side.

release: Add extension filter for store/group

---

src/commands/distribute/release.ts
test/commands/distribute/release/release-test.ts

This is allowed for Google Play and distribution groups.
This check avoids getting a 400 error which was then badly
translated as:
"changing distribution group is not supported"

release: Skip empty release notes

---

package-lock.json
src/commands/distribute/groups/publish.ts
src/commands/distribute/stores/publish.ts
test/commands/distribute/fakes.ts
test/commands/distribute/groups/publish-test.ts
test/commands/distribute/stores/publish-test.ts

Groups support all file formats (except .aab) and may require build-version and build-number.
Stores don't support any file format that would require version info.
This should fix #686

Fix build version/number for "publish" ops

---

src/commands/test/lib/parameters-parser.ts
test/commands/test/lib/parameters-parser-test.ts

Handle multiple test_env or app_env test parameters and throw an error if multiple parameters of other types are supplied

Handle multiple test_env or app_env test parameters

---

src/commands/codepush/lib/react-native-utils.ts

This commit fixes https://github.com/microsoft/appcenter-cli/issues/716 by changing react-native path in react-native-utils.ts

react-native-utils changed

---

test/commands/codepush/codepush-release-test.ts
test/commands/codepush/utils.ts

**Issue:** We found that 3 tests for `codepush release` commands are broken in node v12.15.0 and higher. After some investigation, it was found that the problem is in the mocking object `nockedFileUploadServiceRequests`. It contains a `chunk_list` with element 0, which is used in the `appcenter-file-upload-client` and determines the start and end position for `createReadStream`. `start` generated based on `chunk_list` takes the value -512, which leads to an error.
This PR adds a fix that allows you to run tests on node v12+

[Code Push] Fix for codepush release tests

---

src/commands/apps/set-current.ts

When trying to run `appcenter apps set-current` with either `--token` or the `APPCENTER_ACCESS_TOKEN` environment variable the user receives an error saying that `set-current` doesn't support that auth mechanism. The fix is to use `MOBILE_CENTER_CURRENT_APP` but the error doesn't mention that. This PR resolves this so users know how to proceed.

Provide suggested fix in set-current token error

---

src/commands/codepush/lib/react-native-utils.ts

After #726  PR, our customers using windows faced a problem while running the `react-native release` commons (f.e. #759). The main reason of this problem is using the wrong path to `react-native-cli`
This PR fixes it for windows.
However, after this fix, the problem with the monorepository (#716) for windows users continues to be relevant

[CodePush Bug] Fix react-native release

---

src/commands/codepush/lib/react-native-utils.ts

This should fixes #693.
For now, we can't deploy a react-native release on Windows with hermes enabled because the script looks for an executable file without a `.exe` file extension, whereas on Windows, we need a `.exe` extension, throwing an ENOENT error.
Full error:
```
Error: spawn node_modules\hermesvm\win64-bin\hermes ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
at onErrorNT (internal/child_process.js:456:16)
at processTicksAndRejections (internal/process/task_queues.js:77:11)
Emitted 'error' event at:
at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
at onErrorNT (internal/child_process.js:456:16)
at processTicksAndRejections (internal/process/task_queues.js:77:11) {
errno: 'ENOENT',
code: 'ENOENT',
syscall: 'spawn …
```

Fix react-native build with hermes enabled on Windows

---

src/commands/test/lib/help-messages.ts

Clarify in help that you must use `--test-output-dir` when using `--merge-junit-xml` in `test run appium` or `--merge-nunit-xml` in `test run uitest`.
Resolves #635

Add required parameter combination to help

---

src/commands/distribute/groups/update.ts
test/commands/distribute/groups/update-test.ts

Add `public` and `private` switches to `distribute groups update`. These allow making a group public or the opposite.
Resolves #642.

Allow changing whether a distribution group is public.

---

src/commands/distribute/groups/update.ts

The `private` switch of `distribute groups update` was meant to be called `no-public` until we discovered this won't work with the current design. There is still an error message referring to it under this name. This changes that.

Fix reference to wrong name of parameter

---

package.json
scripts/autorest.js

Here's a first PR that actually solves running Autorest (version 2) using 16Gb of memory for node.
Tested with node 10.
A follow-up PR will update the client APIs.

Run autorest with 16Gb

---

.github/workflows/codeql-analysis.yml

Adds a GitHub Actions workflow that runs CodeQL on every push, and on a daily schedule.
Code scanning looks for vulnerabilities, such as XSS, SQL injection, etc., in your code. If it finds any new vulnerabilities it surfaces them in the PR as check annotations, and blocks the build until they’re fixed or marked as false positives. If it finds any on the repo’s default branch it displays them in the security tab.
For now you also need to be feature flagged individually to see results in the security tab (as well as having write permission on this repo) - if you drop an email to jhutchings1@github.com I can get anyone you need added.
Finally, this is an early access program that has not been released yet, so please don't share before May 6th when we’re unveiling it at GitHub Satellite.
Cc: …

Add CodeQL Analysis workflow

---

.github/workflows/codeql-analysis.yml

As part of https://github.com/microsoft/appcenter-cli/pull/840 I used the autobuild feature which yielded Java. Manually specifying JavaScript (TypeScript) only.
This fixes https://github.com/microsoft/appcenter-cli/runs/629079947
Apologies for the double PRs, but this only surfaced after the PR was merged.

Explicitly specify JS for Code analysis

---

src/commands/apps/get-current.ts
src/commands/lib/logout.ts
src/util/commandline/app-command.ts

The user (profile) will be `null` when using the `APPCENTER_ACCESS_TOKEN` environment variable.
Resolves #844.

Check for `null` user before using its properties

---

README.md
src/commands/distribute/releases/edit-notes.ts
test/commands/distribute/releases/edit-notes-test.ts

Add the command to the readme.
Require exactly one of the release notes parameters.

Minor update to `distribute releases edit-notes`

---

package-lock.json
package.json

Changes:
- Added new command `appcenter distribute releases edit-notes` by @Vacxe in #853 
- Reverted `uuid` to v7 to fix issues with `appcenter login` on some platforms, see #861

Version 2.5.2 with hotfix for login and edit-notes

---

test/functional/Invoke-FunctionalTests.ps1

We have the following WARNING with latest Pester:
> You are using Legacy parameter set that adapts Pester 5 syntax to Pester 4 syntax. This parameter set is deprecated, and does not work 100%. The -Strict and -PesterOption parameters are ignored, and providing advanced configuration to -Path (-Script), and -CodeCoverage via a hash table does not work. Please refer to https://github.com/pester/Pester/releases/tag/5.0.1#legacy-parameter-set for more information.
This then leads to the following error:
```
[-] distribute release.creates a release when mandatory flag is set to true 1.26s (1.26s|3ms)
JsonReaderException: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.
ArgumentException: Conversion from JSON failed with error: Unexpected character …
```

Fix functional tests: require pester 4.x

---

src/commands/test/lib/test-cloud-uploader.ts

Get app info to determine if owner is org instead of listing all orgs. This will allow App API token usage with the `test` commands.

Fix "isOrg" check in test command

---

src/commands/distribute/lib/mc-fus-uploader/mc-fus-uploader-types.ts
src/commands/distribute/lib/mc-fus-uploader/mc-fus-uploader.ts

When uploading a file with a path, the full path was sent to the server as a filename. Fix this, by extracting the only filename for sending to the server.

Extract a filename from path

---

src/commands/distribute/release.ts

This PR makes sure that a `--token` parameter is used when specified.
This also fixes several unit tests which were failing if user is not logged in on the machine.

Use token parameter in release command

---

src/commands/distribute/release.ts

This kind of logic introduced a bug before:
- Logout
- Use distribute command with the token provided
- Endpoint is undefined.

Fix getting the proper endpoint

---

src/commands/apps/lib/format-app.ts
src/commands/orgs/apps/create.ts
test/commands/orgs/apps/create-test.ts

It's a clone of `apps create`, except it catches exceptions for nicer user errors and has unit tests. Functional tests probably would have been better, but/since that required creating `orgs delete` and `orgs apps delete` commands as well.
Resolves #831.
Involves #712.

Add `orgs apps create` command.

---

.github/dependabot.yml
.github/dependabot.yml.

Dependabot version update is now in beta, see post at:
https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/
Once this flow has been validated, we can remove the dependabot-preview app.
We may have to check in some changes to tell dependabot not to ignore this or that package, as we've previously done with comment in the PRs raised. With a bit of luck, the bot will have the right to run builds on azure pipelines.
See also:
- https://help.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates
- https://help.github.com/en/github/administering-a-repository/customizing-dependency-updates

Add dependabot.yml to enable dependabot beta

---

src/commands/distribute/release.ts
test/commands/distribute/release/release-test.ts

Add a check for the status code of the response and process it accordingly to avoid retrying when receiving error response.

loadReleaseIdUntilSuccess retries on 500 error response

---

appcenter-file-upload-client-node/package-lock.json
appcenter-file-upload-client-node/package.json
azure-pipelines.yml

The appcenter-file-upload-client-node package is already built as part of building the main CLI package.
Now the build pipeline also runs its tests and verifies their running and results.
This adds only a couple of seconds to a pipeline running a couple of minutes. No need to separate things out.

Test appcenter-file-upload-client-node package in build pipeline

---

src/commands/distribute/groups/publish.ts
src/commands/distribute/stores/publish.ts
test/commands/distribute/groups/publish-test.ts
test/commands/distribute/stores/publish-test.ts

Fixes in issue where `distribute release` with `--token` works but `distribute groups publish` does not (with a 403) due to not forwarding params from the groups/publish task.

Fixes passing token/env into release task from group publish

---

src/commands/codepush/lib/react-native-utils.ts
src/commands/codepush/lib/validation-utils.ts
src/commands/codepush/release-react.ts

**Issue:**  Hermes path, it changed in the RN 0.63 release (because they upgraded Hermes from 0.4.0 to 0.5.0).
**Solution:** Update path for new versions.
**Related issue:** #1017 [#1886](https://github.com/microsoft/react-native-code-push/issues/1886)

[CodePush] Fix Hermes path for new version

---

package-lock.json
package.json

The changes since the last version number bump include the new attempt at turning the mcfus code into a truly external npm package, although the code is still in this repo. The rest of the changes are dependency updates.

Version number to 2.6.7

---

appcenter-file-upload-client-node/index.ts
appcenter-file-upload-client-node/package-lock.json
appcenter-file-upload-client-node/package.json
appcenter-file-upload-client-node/src/ac-fus-uploader.ts
appcenter-file-upload-client-node/src/ac-fus-util.ts
appcenter-file-upload-client-node/tests/unit/ac-fus-util-tests.ts

This PR adds proxy environment variables support to **appcenter-file-upload-client-node** using [proxy-agent](https://github.com/TooTallNate/node-proxy-agent/) package. It should fix [the problem with uploading releases using a proxy](https://github.com/microsoft/appcenter-cli/issues/982).
This PR also bumps the package version. After the PR is reviewed and tested we should publish an update to npmjs and update the dependency of the appcenter-cli and use the new `fetchWithOptions` method instead of 'fetch'. There's a [draft PR](https://github.com/microsoft/appcenter-cli/pull/1045) for it.
How to test:
1. Add an environment variable 'https_proxy' with proxy settings.
```
export https_proxy=http://xx.xx.xx.xx:port
```
2. `cd appcenter-file-upload-client-node && npm pack`
3. install the …

Add proxy variables support to appcenter-file-upload-client-node

---

.vscode/launch.json
contributing.md
package.json

**Updates**
1. `npm run build` runs the linter every time wasting time when debugging. So, created `npm run compile` to use it when debugging.
2. `node2` is outdated, so updated it to `node`.  
3. Add a section to explain how to use debugging configurations defined in `launch.json` in the contribuding.md. 
4. Created a new debugging config, `Launch without building sourcemaps` to use when there's no change in source code. It reduces time to build sourcemaps as it's not necessary.

Make appcenter-cli debugging easier

---

package.json
src/commands/distribute/release.ts

This PR updates **appcenter-file-upload-client-node** dependency and applies the new 'fetchWithOptions' method from https://github.com/microsoft/appcenter-cli/pull/1044.
It should be merged after the **appcenter-file-upload-client-node** is updated to 1.1.0 in the npm registry.
Related work items:
Original issue: #982
[AB#81897](https://msmobilecenter.visualstudio.com/Mobile-Center/_boards/board/t/IvanM-Team/Backlog%20Items/?workitem=81897)

Add proxy variables support to fetch calls in the CLI

---

.github/dependabot.yml

This would explain why we still have many outdated dependencies, and fix that.

Open PRs for all dependency updates (not just five)

---

src/commands/codepush/lib/react-native-utils.ts
src/commands/codepush/lib/validation-utils.ts

This fix resolves these issues:
https://github.com/microsoft/react-native-code-push/issues/1676
https://github.com/microsoft/react-native-code-push/issues/1939
I've used `semver.coerce()` to clear version string. Now `mobiletechvn/react-native#v0.63.2.fix-shadow-node` or `^0.63.2` will transform into `0.63.2`. And Hermes version will be checked correctly.

[code-push] [release-react] fix version with caret and react-native custom build

---

package.json
src/commands/distribute/release.ts
test/commands/distribute/release/release-test.ts

Context: We are deprecating `PATCH /v0.1/apps/{owner_name}/{app_name}/release_uploads/{upload_id}` API ([openapi.appcenter.ms swagger link](https://openapi.appcenter.ms/#/distribute/releaseUploads_complete)). When calling App Center CLI with incorrect build number or incorrect build version (see command below), the CLI will call the deprecated PATCH API with `aborted` on file upload failure. Note this bug only reproduces when both build version and build number parameters are provided but at least one of them is invalid.
`appcenter distribute release --file <localFilePath> --app <appName> --group <groupName> --build-version <build-version> --build-number <build-number>`
We investigated the distribute backend and discovered the `aborted` release upload status is never used in any …

[Distribution] Do not call abortReleaseUpload API when uploading file failed

---

src/commands/codepush/deployment/list.ts
src/util/misc/promise-map.ts

**Issue**: `deployment list` command gets the list of the deployments (which works flawlessly as this is one request) and then for each deployment tries to get metrics info if `latest_release` field of the deployment is not empty by sending request-per-deployment simultaneously. The server in that case returns 429 error "Too many requests".
**Solution**: Limit the number of requests per time.

[CodePush] Add limit for request

---

test/functional/commands/distribute/Release.Tests.ps1

The distribute functional tests are flaky at the moment. Sometimes the [tests fail](https://msmobilecenter.visualstudio.com/Mobile-Center/_build/results?buildId=1004359&view=logs&j=50448a2f-9550-51a0-b6c4-5ec64224dd81&t=14e66476-54b5-552b-93fd-083932f3d78f&s=b15d9194-8f26-5328-b47f-5968c76b37e7) with the following message:
```
Error message
Conversion from JSON failed with error: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.
Stack trace
at <ScriptBlock>, /home/vsts/work/1/s/test/functional/commands/distribute/Release.Tests.ps1: line 16 16: $r1 = appcenter distribute release -g Collaborators -f $fileName --build-version 1 --mandatory --output json | ConvertFrom-Json
```
Additional logging will help us narrow down the problem. …

Add logs to the distribute functional tests

---

src/commands/codepush/lib/react-native-utils.ts
test/commands/codepush/release-react-test.ts

**Issues:**
https://github.com/microsoft/appcenter-cli/issues/1249
https://github.com/microsoft/appcenter-cli/issues/634
https://github.com/microsoft/appcenter-cli/issues/1138
Android codepush release command fails when running:
`return Array.from(buildGradle["project.ext.react"]).includes("enableHermes: true");` because the `buildGradle["project.ext.react"] ` may not exist in build.gradle file.

[CodePush] Fix release issue

---

src/commands/distribute/lib/distribute-util.ts
src/commands/distribute/release.ts
test/commands/distribute/lib/distribute-util-test.ts
test/commands/distribute/release/release-test.ts

This PR adds support for specifying multiple distribution groups when executing the `appcenter distribute release` command. the `-g` command now supports comma-delimited lists of groups. For example:
- `-g thisgroup,thatgroup`
- `-g thisgroup,"group with spaces"`
**Changelog description:**
> Flexible distribution: The CLI tool now supports distributing a release to multiple distribution groups.
I believe I have covered all my bases, but let me know if any changes/additions should be made.
Fixes #662

Add support for distributing releases to multiple distribution groups

---

src/commands/distribute/release.ts
src/index.ts
test/functional/commands/distribute/Release.Tests.ps1

This PR fixes an output when an error occurs and `--output json` has been specified.
Before:
```
appcenter distribute release -f release.apk --output json
Error: At least one of '--group' or '--store' must be specified
```
After:
```
appcenter distribute release -f release.apk --output json
{"succeeded":false,"errorCode":4,"errorMessage":"At least one of '--group' or '--store' must be specified"}
```
Aside from that it:
- improves the Distribute functional test
- fixes Distribute release notes error message
Related issues:
https://github.com/microsoft/appcenter-cli/issues/1207
https://github.com/microsoft/appcenter-cli/issues/768
[AB#84915](https://msmobilecenter.visualstudio.com/Mobile-Center/_boards/board/t/Ivan-Team/Backlog%20Items/?workitem=84915)

Fix json output for an error

---

src/commands/test/lib/uitest-preparer.ts

This PR should extend the "Test chunking failed" error message, in order to give customers more informative message about a probable solution for this error.

Update test chunking failed error messsage

---

src/commands/codepush/lib/cordova-utils.ts

Enhance error handling for cordova config.xml parsing.
If config.xml is empty or missing the expected `<widget/>` tag, the errors were unclear.
Before:
`Command Failure at TypeError: Cannot read property '$' of undefined`
`Command Failure at TypeError: Cannot read property 'widget' of null`
After:
`Command Failure at Error: Unable to parse "config.xml" in the CWD. Ensure that the contents of "config.xml" is valid.`

CodePush Cordova: Enhance error handling for config.xml parsing

---

src/util/profile/profile.ts

Context: https://github.com/microsoft/appcenter-cli/issues/1218/
When appcenter cli tries to fetch data from token-store it fallbacks to an old service name ignoring the command error output. It assumes that if the command failed then the service name was not found, so it tries to search for an old service name and then throws an error if there is any. 
However, in this scenario the error message will always be security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
See https://github.com/microsoft/appcenter-cli/blob/master/src/util/profile/profile.ts#L59
We should check what was the error and if it was not a "could not be found" error, then throw it and don't fall back to an old service name.
[AB#85233](https://msmobilecenter.visualstudio.com/Mobile-Cen …

Fix swallowed error output for access token getter

---

bin/appcenter.js

The [previous fix](https://github.com/microsoft/appcenter-cli/pull/1278) was missing the actual entry point fix. Here it is.
This PR fixes an output when an error occurs and `--output json` has been specified.
Before:
```
appcenter distribute release -f release.apk --output json
Error: At least one of '--group' or '--store' must be specified
```
After:
```
appcenter distribute release -f release.apk --output json
{"succeeded":false,"errorCode":4,"errorMessage":"At least one of '--group' or '--store' must be specified"}
```
Related issues:
https://github.com/microsoft/appcenter-cli/issues/1207
https://github.com/microsoft/appcenter-cli/issues/768
[AB#85783](https://msmobilecenter.visualstudio.com/Mobile-Center/_boards/board/t/Ivan-Team/Backlog%20Items/?workitem=85783)

Fix entry point error logging

---

package-lock.json
package.json

- Recommended Node.js version is 12
- Json output bug fix
- Dependency updates.
Difference: https://github.com/microsoft/appcenter-cli/compare/v2.8.1...af44367a6ef25cf38c2843ab1d3840b4cce4252c

Version number to 2.9.0

---

src/commands/codepush/deployment/list.ts

**Issue**: Now server returns a list of deployments with the `latestRelease` property for and metrics. CLI tries to add the new field `metrics` for the undefined property `latestRelease`.
**Solution**: Add one more condition for checking that the `latestRelease` isn't undefined.

Modify condition

---

package-lock.json
package.json

This PR bumps lib version to 1.2.1 (contains updated logging for WI AB#86279).

Bump appcenter-file-upload-client-node to 1.2.1

---

src/commands/codepush/deployment/list.ts

We should return PROMISE_CONCURRENCY to prev version because it's not an effective strategy for the customer.
[AB#86388](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/86388)
[AB#85283](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/85283)

Return previous value for PROMISE_CONCURRENCY

---

src/commands/codepush/lib/react-native-utils.ts

Issue: In case of package.json file have no dependencies or doesn't have this section - codepush  fails when trying to determine the version of React Native.
Ref: #1485
Solution: Corrected dependency check logic.

[CodePush] Corrected dependency check

---

src/commands/codepush/lib/react-native-utils.ts
src/commands/codepush/release-react.ts

Issue: In multi workspaces code structure, if the app is in a child folder and all dependencies is declared from root folder. I will need to run the command from root folder. In this case the file project.pbxproj will not be found in these paths: "ios/my-app.xcodeproj/project.pbxproj", "ios/project.pbxproj".
Ref: #851
Solution: Add a param to let user to manually specify path to to Xcode project or project.pbxproj file.

[CodePush] release-react: add param to specify path to Xcode project file

---

src/commands/test/lib/uitest-preparer.ts

This PR fixes the argument name in the following error message:
> Error: If keystore is used, all of the following arguments must be set: --store-file, --store-password, --key-alias, --key-password
`--store-file` argument name is no more used, so it has been replaced with correct argument name `--store-path`.

Correcting argument name of error output

---

src/commands/test/lib/uitest-preparer.ts
src/util/misc/process-helper.ts
test/commands/test/run/uitest-test.ts

This PR fixes the following security warning:
> Shell command built from environment values
> Building a shell command string with values from the enclosing environment may cause subtle bugs or vulnerabilities.
The solution is to replace `exec` with `execFile`, providing a command and arguments separately.

[test-cloud] Generate a shell command safely for xamarin uitest

---

src/commands/distribute/release.ts

Modified the error message for the release command, clarifying that the message is from a backend response.
[AB#87912](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/87912)

[Distribute]Add backend response for error description

---

appcenter-file-upload-client-node/package-lock.json
appcenter-file-upload-client-node/package.json

This PRs bumps version to 1.2.2 in order to publish new package - `proxy-agent@4.0.1` dependency from 1.2.1 discovered to be vulnerable https://github.com/advisories/GHSA-9j49-mfvp-vmhm - which is fixed in `proxy-agent@5.0.0` https://github.com/TooTallNate/node-proxy-agent/releases/tag/5.0.0

[appcenter-file-upload-client-node] bump version to 1.2.2

---

package-lock.json
package.json

This PR bumps lib version to 1.2.2

Bump appcenter-file-upload-client-node to 1.2.2

---

appcenter-file-upload-client-node/package-lock.json
appcenter-file-upload-client-node/package.json

This PRs bumps version to 1.2.3 in order to include new changes presented in the following PRs:
https://github.com/microsoft/appcenter-cli/pull/1688/files
https://github.com/microsoft/appcenter-cli/pull/1697/files

[appcenter-file-upload-client-node] bump version to 1.2.3

---

src/commands/distribute/groups/download.ts
test/commands/distribute/groups/download-test.ts

**Current behavior:**
Obtaining a `downloadUrl` for downloading a release takes place in 2 stages: getting a list of releases for a distributionGroup (max 200) and if the required release is in the list, then a `downloadUrl` will receive.
**The problem:**
The max count of releases is 200. If more than 200 releases have been distributed to the distributionGroup, then the customer receives an error: "release XX was not distributed to distribution group GROUP_NAME".
**The solution:**
Fixed getting `downloadUrl` for release in one request: [/v0.1/apps/{owner_name}/{app_name}/distribution_groups/{distribution_group_name}/releases/{release_id}](https://openapi.appcenter.ms/?url=https%3A%2F%2Fapi.appcenter.ms%2Fpreview%2Fswagger-internal.json#/distribute/releases_getLatestByDistributionGroup)

Fixed getting release for distributionGroup

---

appcenter-file-upload-client-node/package-lock.json
appcenter-file-upload-client-node/package.json

This PRs bumps version to 1.2.3 in order to include new changes presented in the following PRs:
https://github.com/microsoft/appcenter-cli/pull/1732
https://github.com/microsoft/appcenter-cli/pull/1726

[appcenter-file-upload-client-node] bump version to 1.2.4

---

src/commands/codepush/lib/react-native-utils.ts

Noticed that despite Hermes being enabled I wasn't seeing the `appcenter-cli` try to create Hermes bytecode for the build -- this was because the check for Hermes was too specific -- it expects:
```
:hermes_enables => true
```
when equally valid is new Ruby syntax:
```
hermes_enabled: true
```
This change adds the latter case as well to the test.

Fix Hermes enabled check for iOS

---

bin/appcenter.js
src/index.ts

When using appcenter CLI in scripts, CLI's errors are not reported to stderr
This causes error stream logs to be missed out.
The script reports all errors to stdout

Print errors on console.error

---

appcenter-file-upload-client-node/package-lock.json
appcenter-file-upload-client-node/package.json

As a part of component governance, need to bump node-fetch to ~2.6.7

[appcenter-file-upload-client-node] bump version to 1.2.5

---

src/commands/test/download.ts
src/commands/test/run/uitest.ts

Fix merge-nunit-xml issue
Related issue: [1208](https://github.com/microsoft/appcenter-cli/issues/1208)

Fix merge-nunit-xml issue

---

appcenter-file-upload-client-node/package-lock.json
appcenter-file-upload-client-node/package.json
package-lock.json
package.json

Fixed security issues:
[CVE-2021-23382](https://github.com/advisories/GHSA-566m-qj78-rww5)
[CVE-2021-23566](https://github.com/advisories/GHSA-qrpm-p2h7-hrv2)

Fix security issues in nanoid and  copy-props for appcenter-cli and appcenter-file-upload-client-node

---

appcenter-file-upload-client-node/package-lock.json
appcenter-file-upload-client-node/package.json

This PRs bumps version of appcenter-file-upload-client-node to 1.2.6 in order to include package update changes.

[appcenter-file-upload-client-node] bump version to 1.2.6

---

src/commands/test/lib/templates/appium/android/pom.xml
src/commands/test/lib/templates/appium/android/src/test/java/com/azure/mobile/app/test/LaunchTest.java
src/commands/test/lib/templates/appium/ios/pom.xml
src/commands/test/lib/templates/appium/ios/src/test/java/com/azure/mobile/app/test/LaunchTest.java

This PR fixes the following vulnerability issues:
CVE-2022-22965                          |org.springframework:spring-beans 5.1.6.RELEASE|Critical                     
CVE-2022-22965                          |org.springframework:spring-core 5.1.6.RELEASE|Critical                   
CVE-2014-0114                           |commons-beanutils:commons-beanutils 1.9.2|High                       
CVE-2019-10086                          |commons-beanutils:commons-beanutils 1.9.2|High                   
CVE-2020-11979                          |org.apache.ant:ant 1.10.3               |High                      
CVE-2022-24785                          |moment 2.29.1                           |High                        
WS-2021-0419                            |com.google.code.gson:gson 2.8.5 …

Fix Appium template

---

src/commands/test/lib/templates/appium/android/pom.xml
src/commands/test/lib/templates/appium/ios/pom.xml

This PR fixes the following vulnerability issues:
https://github.com/advisories/GHSA-36p3-wjmg-h94x |org.springframework:spring-beans 5.1.6.RELEASE|Critical
https://github.com/advisories/GHSA-36p3-wjmg-h94x |org.springframework:spring-core 5.1.6.RELEASE|Critical
https://github.com/advisories/GHSA-f62v-xpxf-3v68 |org.apache.ant:ant 1.10.3 |High
https://github.com/advisories/GHSA-8hfj-j24r-96c4 |moment 2.29.1 |High
WS-2021-0419 |com.google.code.gson:gson 2.8.5 |High
https://github.com/advisories/GHSA-7r82-7xv7-xcpj |org.apache.httpcomponents:httpclient 4.5.8|Medium
https://github.com/advisories/GHSA-4p6w-m9wc-c9c9 |org.apache.ant:ant 1.10.3 |Medium
CVE-2021-22096 |org.springframework:spring-core 5.1.6.RELEASE|Medium
https://github.com/advisories/GHSA-q5r4-cfpx-h6fh |org.apache.ant:ant …

Update versions of vulnerable packages

---

src/commands/codepush/lib/react-native-utils.ts

There can be many cases where the line does not exactly match the `enableHermes: true`.
I don't think these changes would be the ultimate solution though 😓 
Case 1
```gradle
project.ext.react = [
entryFile   : "index.js",
enableHermes: true  // Enable hermers
]
```
Case 2
```gradle
project.ext.react = [
enableHermes: true,
entryFile   : "index.js",
]
```

Fix getAndroidHermesEnabled

---

src/commands/build/download.ts

Adding download of .aab application file for Android.
pre:
```
> docker run --rm -it node /bin/bash
(in container)
> npm install -g appcenter-cli
> appcenter login --token user-token
```
tested
```
> appcenter build download -i 1337 --app ORG/APP.Android -t bundle --debug
(output)
Downloaded content was saved to /tmp/bundle_APP.Android.aab
```

Add ability to download bundle (.aab file)

---

README.md

I received the following warning when installing appcenter-cli on npm version 8.11.0
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

use --location=global (npm config deprecation)

---

src/commands/codepush/lib/electron-utils.ts
src/commands/codepush/lib/react-native-utils.ts
test/commands/codepush/release-react-test.ts

This PR aims at fixing issue #911.
In subprocesses' `'close'` event handlers:
```javascript
.on("close", (exitCode: number, signal: string) => { ... }
```
By checking that `exitCode` is `!== 0`, we handle the cases where `exitCode` is `null` and `signal` is defined.
References:
- https://nodejs.org/api/child_process.html#class-childprocess
- https://stackoverflow.com/questions/39159312/child-process-exits-with-code-null
Reopened from https://github.com/microsoft/appcenter-cli/pull/2004 with fixes in ui tests.

Codepush: Handle subprocess error cases where exitCode is null.

---

src/commands/codepush/deployment/history.ts
test/commands/codepush/deployment/history-test.ts

Hi,
When running the `appcenter codepush deployment history Deployment --app Org/App` command when Org/App exists but does not have a deployment called "Deployment" I get the following error output:
```sh
{"succeeded":false,"errorCode":6,"errorMessage":"The app Org/App does not exist. Please double check the name, and provide it in the form owner/appname. \nRun the command \u001b[1mappcenter apps list\u001b[22m to see what apps you have access to."}
``` 
This error message is misleading since it tells the user that the app does not exist, and in this case it's the deployment that does not exist. 
I ran the command with the `--debug` flag to understand what result was returned from the backend, and I got this output:
```sh
Using appcenter-cli version: 2.11.0
logFilter, request: { …
```

Fix non existing deployment error message

---

src/commands/codepush/release-react.ts
test/commands/codepush/release-react-test.ts

With this PR users can bypass hermes checks and force enable it using `--use-hermes` arg
Fixes https://github.com/microsoft/appcenter-cli/issues/2112

Add --use-hermes arg to bypass hermes checks and force enable it

---

.github/workflows/codeql-analysis.yml

Upgrade codeql actions to v2.
> Warning: CodeQL Action v1 will be deprecated on December 7th, 2022. Please upgrade to v2. For more information, see https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
Also, filter CodeQL on.push and on.pull_request scan to `master` branch only. Note, for pull requests this filter means the Target branch, not the one the pull request was created from.
The error:
> Error: Workflows triggered by Dependabot on the "push" event run with read-only access. Uploading Code Scanning results requires write access. To use Code Scanning with Dependabot, please ensure you are using the "pull_request" event for this workflow and avoid triggering on the "push" event for Dependabot branches. See …

Upgrade codeql action to v2

---

src/commands/codepush/release-react.ts

[release-react] Do not generate sourcemaps if only `output-dir` is specified and neither `sourcemap-output` nor `sourcemap-output-dir` are specified.
Please tell me if you have any remarks or suggestions about this PR.

[release-react] Do not generate sourcemaps if only `output-dir` is specified

---

appcenter-file-upload-client-node/package-lock.json
appcenter-file-upload-client-node/package.json

This PR bumps the version of `appcenter-file-upload-client-node` to `1.2.7` in order to include package update changes.

[appcenter-file-upload-client-node] bump version to 1.2.7

---

package-lock.json
package.json

Fixes WS-2023-0004 zip-slip vulnerability.
[AB#98058](https://dev.azure.com/msmobilecenter/Mobile-Center/_workitems/edit/98058)

Update jszip to 3.8.0

---

src/commands/test/generate/uitest.ts
src/commands/test/lib/templates/uitest/android/AppCenter.UITest.Android/AppCenter.UITest.Android.csproj
src/commands/test/lib/templates/uitest/android/AppCenter.UITest.Android/packages.config
src/commands/test/lib/templates/uitest/ios/AppCenter.UITest.iOS/AppCenter.UITest.iOS.csproj
src/commands/test/lib/templates/uitest/ios/AppCenter.UITest.iOS/packages.config
test/commands/test/generate/uitest-test.ts

This PR fixing autogenerating `XamarinUITes`t Project, added support of `.NET6`, changed test for this.

Fix autogenerating XamarinUITest project

---

src/commands/codepush/lib/react-native-utils.ts

Currently when pushing codepush update with hermes enabled it calls file `compose-source-maps.js` directly, problem will arise when you call js file directly on windows it will causing exception and causing failed to release codepush update. Instead calling `compose-source-maps.js` I think it's better to call with node command

[Codepush][Hermes] Fixing compose-source-maps command calls

---

src/commands/test/run/appium.ts
src/commands/test/run/manifest.ts

Using the option  --merged-file-name "output.xml" --test-output-dir JunitTestResult, facing the below issue.
Same for --merge-junit-xml  "output.xml" --test-output-dir JunitTestResult
i can see .zip was was downloaded but merged files is not working!
Downloaded artifacts to JunitTestResult\junit_xml_zip.zip 
Error: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Document
Similar issue with nunit for xamarin uitest: https://github.com/microsoft/appcenter-cli/pull/1814

 Fix merge-junit-xml and merge-nunit-xml issue

---

azure-pipelines.yml

The PR adds a condition for functional tests so we need to set the RUN_FUNCTIONAL_TESTS variable to `true` if we need tests to run.

Run functional tests only if variable is set

---

appcenter-file-upload-client-node/package-lock.json
appcenter-file-upload-client-node/package.json
package-lock.json
package.json

Bump VM2 package to fix vulnerability
AB#[100513](https://dev.azure.com/msmobilecenter/Mobile-Center/_workitems/edit/100513)

Version 2.13.6 for appcenter-cli and Version 1.2.9 for appcenter-file-upload-client node

---

src/commands/codepush/lib/react-native-utils.ts

We were facing issues with the appcenter cli after migrating our react-native project to a mono-repository.
The cli is looking for react-native package is in the project node_modules folder instead of the root node_modules, which leads to errors.
This PR aims to solve that by using node's `require.resolve` to find the package path.

Use node to resolve react-native package path 

---

src/commands/codepush/deployment/list.ts

When getting the list of deployments from appcenter the command failed with an error message that failed to get deployments .
This is happening because of the nested calls the appcenter-cli does to fetch metrics for each deployment if you have a considerable deployment list then the nested calls to fetch metric info of each deployment exceeds the API rate limiting due to which the command fails
I have added another option to the list command which disables nested API calls for metric info.

feat: added additional option to disable nested api cals when getting list of deployments

---

appcenter-file-upload-client-node/package-lock.json
appcenter-file-upload-client-node/package.json
appcenter-file-upload-client-node/src/ac-fus-util.ts
appcenter-file-upload-client-node/tests/unit/ac-fus-util-tests.ts
azure-pipelines.yml

[AB#101802](https://dev.azure.com/msmobilecenter/Mobile-Center/_workitems/edit/101802)
- Fix CVE-2023-37466 in vm2 3.9.19. Severity: Critical
- Update Node version on Azure pipelines
- Update Typescript version for updated Proxy-Agent package

[appcenter-file-upload-client node] Remove deprecated VM2 package

---

appcenter-file-upload-client-node/package-lock.json
appcenter-file-upload-client-node/package.json

[AB#101802](https://dev.azure.com/msmobilecenter/Mobile-Center/_workitems/edit/101802)
- Fix CVE-2023-37466 in vm2 3.9.19. Severity: Critical
- Update Node version on Azure pipelines
- Update Typescript version for updated Proxy-Agent package

Version 1.2.11 for appcenter-file-upload-client node

---

README.md
appcenter-file-upload-client-node/package-lock.json
appcenter-file-upload-client-node/package.json
contributing.md
package.json

[AB#102566](https://msmobilecenter.visualstudio.com/Mobile-Center/_boards/board/t/SDK/Backlog%20Items/?workitem=102566)
Bump of minimal NodeJS version required by [PR#2387](https://github.com/microsoft/appcenter-cli/pull/2387) where fix https://github.com/advisories/GHSA-cchq-frgv-rjh5 in vm2 3.9.19. Severity: Critical has been implemented.

Bump NodeJS to 14

---

src/commands/codepush/release-react.ts

Update the command description to reflect the latest state of the code.
`output-dir` has no effect on the generated source maps destination.

fix(help): Release React command update `output-dir` help desc

---

src/commands/login.ts

This PR resolves an issue with the login command. Although `appcenter login` currently reports success, it fails to save the token, causing authorization errors in subsequent commands.
Using locally set `token` instead of `this.token` solves the issue.

Fix login command

---

.azurepipelines/appcenter-cli-1ES.yml

[AB#104414](https://dev.azure.com/msmobilecenter/Mobile-Center/_boards/board/t/Mobile%20SDK%20team/Backlog%20Items/?workitem=104414)

[Pipeline] Split CI and PR template, move yml

---

package-lock.json
package.json

Updating ms-rest-js to v2.7.0 removes punycode from appcenter-cli's dependencies.
https://github.com/microsoft/appcenter-cli/issues/2470/
[AB#104031](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/104031)

Update ms-rest-js to 2.7.0

---

.azurepipelines/appcenter-cli-1ES.yml
package-lock.json
package.json

This PR includes:
- Upgrades node version to 21
- Run `npm audit fix --force`
Running audit fix with --force is ok, as there are only minor version changes. It requires force, because we specified strict versions for the affected packages.

Use Node 21 and fix vulnerabilities

---

package-lock.json
package.json

Add explicit version for appcenter-file-upload-client-node to 1.2.12

Add explicit version for appcenter-file-upload-client-node to 1.2.12

---

src/commands/apps/delete.ts

Currently delete app command doesn't work since appcenter-cli sends delete request with wrong order of params with this PR this should be fixed
[AB#107373](https://dev.azure.com/msmobilecenter/Mobile-Center/_boards/board/t/Mobile%20SDK%20team/Backlog%20Items/?workitem=107373)

Fix delete app command params order

---

src/commands/test/lib/templates/appium/android/pom.xml
src/commands/test/lib/templates/appium/ios/pom.xml

> This issue affects Apache Commons IO: from 2.0 before 2.14.0.
> Users are recommended to upgrade to version 2.14.0 or later, which fixes the issue.
Current commons-io version: 2.11.0
Updated commons-io version: 2.14.0
More details https://github.com/advisories/GHSA-78wr-2p64-hpwj
[Build](https://dev.azure.com/msmobilecenter/SDK/_build/results?buildId=1546106&view=results)
[#AB107782](https://dev.azure.com/msmobilecenter/Mobile-Center/_workitems/edit/107782)

Fix Apache Commons IO high severity vulnerability
