microsoft/appcenter-cli

- bin/mobile-center.js
- package.json
- src/commands/test/lib/calabash-preparer.ts
- src/commands/test/lib/test-cloud-uploader.ts
- src/commands/test/lib/uitest-preparer.ts
- src/commands/test/prepare/calabash.ts
- src/commands/test/prepare/uitest.ts
- src/util/interaction/prompt.ts
Removed arrow functions from launch script to avoid syntax errors in
node 4.
Fixed debug category strings in test commands to match rest of CLI.
Fixed error in interaction.question function, it wasn't wrapping the
"you can't prompt in quiet mode" exception into a promise properly.
> Misc. bug fixes.

- README.md
- package.json
- src/commands/test/lib/prepare-tests-command.ts
- src/commands/test/lib/run-tests-command.ts
- src/commands/test/prepare/appium.ts
- src/commands/test/prepare/calabash.ts
- src/commands/test/prepare/espresso.ts
- src/commands/test/prepare/uitest.ts
- src/commands/test/run/appium.ts
- src/commands/test/run/calabash.ts
- src/commands/test/run/espresso.ts
- src/commands/test/run/manifest.ts
- src/commands/test/run/uitest.ts
- src/commands/test/status.ts
Also found a bug that would bite linux users, case was wrong in
import statement on filename.
> Updating version, readme for v0.2 release.

- contributing.md
- package.json
We should either merge this or #85 to make this project work without issues in a fresh clone.
> Force TS 2.0 until we are compatible with 2.1

- src/commands/login.ts
- src/util/apis/index.ts
> Add proper erros message when login fails

- src/commands/tokens/delete.ts
Command failed with "missing required parameter" without it.
> Fixed annotation on id property for tokens delete command.

- package.json
- src/util/interaction/out.ts
- src/util/interaction/prompt.ts
- src/util/profile/telemetry.ts
Adding timeout for answer to enable telemetry prompt. Also updated inquirer dependency to latest version.
> Telemetry prompt timeout

- src/commands/test/lib/run-tests-command.ts
- src/commands/test/run/appium.ts
- src/commands/test/run/calabash.ts
- src/commands/test/run/espresso.ts
- src/commands/test/run/manifest.ts
- src/commands/test/run/uitest.ts
No functional changes but I prefer this approach
> Refactor `--app-path` to simplify code

- src/commands/build/category.txt
- src/commands/build/download.ts
- src/util/commandline/command-result.ts
Implemented "build download" command.
This PR depends on https://github.com/Microsoft/mobile-center-cli/pull/129
> Implemented "build download" command

- src/commands/build/logs.ts
> Implemented "build logs" command

- src/commands/build/branches/list.ts
- src/commands/build/branches/show.ts
- src/commands/build/download.ts
- src/commands/build/logs.ts
- src/commands/build/queue.ts
This PR contains fix for the issues defined in [`the task`](https://mseng.visualstudio.com/Mobile%20DevOps/Command%20Line%20Interface/_workitems?id=951458&_a=edit). I have also fixed the error handling in the rest of the 'build' commands - the error handling code was not fired when an error happened, because API requests were failing by throwing an exception instead of returning bad HTTP code.
> Fixed the error handling for the "build" commands

- src/commands/build/branches/lib/format-build.ts
- src/commands/build/branches/list.ts
- src/commands/build/branches/show.ts
- src/commands/build/download.ts
- src/commands/build/logs.ts
- src/commands/build/queue.ts
Implemented change proposed in [the task](https://mseng.visualstudio.com/Mobile%20Center/Command%20Line%20Interface/_workitems?id=951460&_a=edit)
> Renamed "Build Number" to "Build ID" for "build branches" commands

- src/commands/build/branches/lib/format-build.ts
- src/commands/build/branches/list.ts
- src/commands/build/branches/show.ts
- src/commands/build/download.ts
- src/commands/build/logs.ts
- src/util/interaction/out.ts
This PR contains fix for the issues defined in [the task](https://mseng.visualstudio.com/Mobile%20Center/Command%20Line%20Interface/_workitems?id=951472&_a=edit). It also contains JSON output fixes for the rest of the "build" commands.
> Fixed '--output json' for "build" commands

- src/commands/distribute/category.txt
- src/commands/distribute/release.ts
- test/commands/crashes/upload-symbols/upload-symbols-test.ts
- test/commands/distribute/release/release-test.ts
Implemented command according to the specifications.
> Implemented 'distribute release' command

- src/commands/distribute/groups/category.txt
- src/commands/distribute/groups/list.ts
Implemented 'distribute groups list' command according to the specification
> Implemented "distribute groups list" command

- src/commands/distribute/groups/show.ts
- src/util/interaction/out.ts
Please note that the expected output was not yet defined when the pull request was created
> Implemented "distribute groups show" command

- src/commands/distribute/groups/create.ts
- src/commands/distribute/groups/show.ts
- src/util/interaction/out.ts
> Implemented 'distribute groups create' command

- src/commands/distribute/groups/create.ts
- src/commands/distribute/groups/lib/email-list-string-helper.ts
- src/commands/distribute/groups/lib/group-view-helper.ts
- src/commands/distribute/groups/show.ts
- src/commands/distribute/groups/update.ts
- src/util/interaction/out.ts
> Implemented 'distribute groups update' command

- src/commands/distribute/groups/delete.ts
> Implemented 'distribute groups delete' command

- src/commands/distribute/releases/list.ts
> Implemented 'distribute releases list' command

- src/commands/distribute/releases/show.ts
> Implemented 'distribute releases show' command

- src/commands/test/generate/appium.ts
> Fixed 'test generate appium' command help message

- package.json
- src/commands/crashes/lib/symbols-uploading-helper.ts
- src/commands/crashes/upload-missing-symbols.ts
- src/commands/crashes/upload-symbols.ts
> Implemented "crashes upload-missing-symbols" command

- scripts/autocomplete-tree.js
> Fixed project building when "dist" was not yet compiled

- src/commands/apps/create.ts
Added lists of supported values to the "-o" and "-p" parameters help of "apps create" command
> Updated "apps create" command help

- src/commands/lib/logout.ts
- src/commands/login.ts
In prep for "suicidal token" endpoint on the back end.
> Delete web supplied login token on future logins

- README.md
- package.json
> Updating for release 0.9

- bin/mobile-center.js
- src/commands/setup-autocomplete.ts
> Fixed autocomplete for zsh and fish shells

- src/commands/orgs/create.ts
- src/util/portal/portal-helper.ts
> Implemented "orgs create" command

- src/commands/orgs/create.ts
- src/commands/orgs/show.ts
- src/util/portal/portal-helper.ts
Implemented command according to the specification.
> Implemented "orgs show" command

- src/commands/orgs/collaborators/list.ts
- src/commands/orgs/create.ts
- src/commands/orgs/lib/org-users-helper.ts
- src/commands/orgs/show.ts
- src/util/portal/portal-helper.ts
> Implemented "orgs collaborators list" command

- src/commands/analytics/audience.ts
> Added headers to the tables returned by "analytics audience"

- src/commands/analytics/sessions.ts
> Added headers to the tables returned by "analytics sessions"

- src/commands/analytics/sessions.ts
> Changed "--duration" parameter name to "--durations"

- src/commands/orgs/collaborators/list.ts
- src/commands/orgs/create.ts
- src/commands/orgs/lib/org-users-helper.ts
- src/commands/orgs/list.ts
- src/commands/orgs/show.ts
- src/util/portal/portal-helper.ts
> Implemented "orgs list" command

- src/commands/orgs/collaborators/list.ts
- src/commands/orgs/create.ts
- src/commands/orgs/lib/org-users-helper.ts
- src/commands/orgs/list.ts
- src/commands/orgs/show.ts
- src/commands/orgs/update.ts
- src/util/portal/portal-helper.ts
> Implemented "orgs update" command

- src/commands/orgs/apps/list.ts
- src/commands/orgs/collaborators/list.ts
- src/commands/orgs/create.ts
- src/commands/orgs/lib/org-users-helper.ts
- src/commands/orgs/list.ts
- src/commands/orgs/show.ts
- src/commands/orgs/update.ts
- src/util/portal/portal-helper.ts
> Implemented "orgs apps list" command

- src/commands/distribute/groups/create.ts
- src/commands/distribute/groups/lib/email-list-string-helper.ts
- src/commands/distribute/groups/update.ts
- src/commands/orgs/apps/list.ts
- src/commands/orgs/collaborators/list.ts
- src/commands/orgs/collaborators/update.ts
- src/commands/orgs/create.ts
- src/commands/orgs/lib/org-users-helper.ts
- src/commands/orgs/list.ts
- src/commands/orgs/show.ts
- src/commands/orgs/update.ts
- src/util/misc/list-of-users-helper.ts
- src/util/portal/portal-helper.ts
> Implemented "orgs collaborators update" command

- src/util/commandline/command.ts
- src/util/portal/portal-helper.ts
- src/util/profile/environments.ts
- src/util/profile/index.ts
See https://github.com/Microsoft/mobile-center-cli/pull/196#discussion_r121190326
> Moved portal endpoints strings to environmentsData

- src/commands/test/lib/run-tests-command.ts
- src/commands/test/lib/state-checker.ts
The changes listed below have been implemented in order to support Jenkins Plugin for Mobile Center Test:
- change printing multiple messages to a single array of messages by using `StreamingArrayOutput`
- replace multiple calls of `out.text` function with a single invocation of `streamingOutput.text` with the converter callback function
> Add simple json output support for progress and status of testing.

- src/commands/orgs/create.ts
> Display name is now required to create organization

- src/commands/orgs/collaborators/list.ts
> Improved "orgs collaborators list" output

- src/commands/orgs/apps/list.ts
- src/commands/orgs/list.ts
- src/commands/orgs/show.ts
"orgs list":
"orgs apps list":
"orgs show":
See #230 and #225
> Updated output for "orgs list", "orgs apps list" and "orgs show" commands

- src/util/commandline/help.ts
> Fixed switches order in command help message

- src/util/interaction/out.ts
> Do not show progress spinner if stdout is not a terminal

- src/commands/analytics/app-versions.ts
- src/commands/analytics/events/show.ts
- src/commands/distribute/groups/list.ts
- src/commands/orgs/apps/list.ts
- src/commands/orgs/collaborators/list.ts
- src/commands/orgs/list.ts
- src/commands/tokens/list.ts
- src/util/interaction/out.ts
"analytics app-versions":
"analytics events show":
"distribute groups list":
"orgs apps list":
"orgs collaborators list":
"orgs list":
"analytics audience":
"analytics sessions":
> Implemented unified output for table commands

- src/commands/login.ts
- src/util/commandline/command.ts
- src/util/profile/environment-vars.ts
- src/util/profile/index.ts
> Implemented correct handling for invalid "--env" value

- src/util/interaction/out.ts
category help:
command help:
Based on #228
> Help for categories and commands is denser now

- src/util/commandline/help.ts
- src/util/interaction/out.ts
> Made command help output consistent with category help output

- src/commands/test/lib/run-tests-command.ts
but had failing test cases. "Command failed: Cannot run Test Cloud tests." is misleading users to think running the tests failed.
> Handle exitCode better. Return accurate error message when tests ran

- src/commands/analytics/category.txt
- src/commands/analytics/lib/analytics-constants.ts
- src/commands/apps/category.txt
- src/commands/build/category.txt
- src/commands/category.txt
- src/commands/crashes/category.txt
- src/commands/distribute/category.txt
- src/commands/help.ts
- src/commands/login.ts
- src/commands/logout.ts
- src/commands/orgs/apps/category.txt
- src/commands/orgs/category.txt
- src/commands/orgs/collaborators/category.txt
- src/commands/profile/category.txt
- src/commands/setup-autocomplete.ts
- src/commands/telemetry/category.txt
- src/commands/test/category.txt
- src/commands/tokens/category.txt
- src/util/commandline/app-command.ts
- src/util/commandline/command.ts
> Simplified descriptions for common categories and options

- scripts/get-commands.js
Automatically do the edits to the command list that I was doing
by hand every release.
> Updated get-commands script to automate edits.

- .gitattributes
- contributing.md
- package.json
- src/util/apis/index.ts
Fixes for #305 plus some updates to contributing file because why not.
> Line ending fix

- src/commands/codepush/lib/update-contents-tasks/zip.ts
- src/commands/codepush/release.ts
1. fix for the "c" parameter
2. fix support for the releasing the single file
> [codepush] fixes for the general "release" command

- src/commands/codepush/lib/release-command-skeleton.ts
As for now we do not consider code signing an experimental feature
> [CodePush] Remove prompt for code-signing

- README.md
- package.json
- src/commands/codepush/rollback.ts
Also fixed a spelling error in the help for codepush deployment
rollback as per https://github.com/Microsoft/appcenter-cli/pull/320
> Updates for release 1.0.3.

- src/commands/codepush/lib/legacy-codepush-service-client.ts
This PR fixes the issue to make a codepush release. Tested in both org/non org apps.
> [BugFix] CodePush: Failed to make a success release

- src/commands/test/generate/uitest.ts
Updates generate command to use new templates.
> Updates the UITest template zip location to point to 1.1

- src/commands/codepush/release-react.ts
This PR including fix for #328
> Fix final deletion of output directory after codepush release-react

- src/util/commandline/category-command.ts
- src/util/commandline/command.ts
> add version to `appcenter help`

- src/util/commandline/app-command.ts
relates to https://github.com/Microsoft/appcenter-cli/issues/343
> improve help message for app parameter

- src/commands/codepush/release-react.ts
relates to https://github.com/Microsoft/code-push/issues/544
> [codepush] fix issue w/ outputDir in case of using code-signing

- test/commands/crashes/upload-symbols/upload-symbols-test.ts
- test/commands/distribute/groups/download/download-test.ts
- test/commands/distribute/release/release-test.ts
Change of testCloudLocalDev environment name broke some of the test suite, this fixes them.
> Fixing up environment names to fix tests

- package-lock.json
- package.json
- src/commands/distribute/release.ts
- src/util/interaction/out.ts
- test/commands/distribute/release/release-test.ts
This PR aims to distribute a new release through new file upload service.
> Distribute release upload file API

- src/util/token-store/osx/osx-token-store.ts
Just a quick fix for the messed up indentation
> Use spaces for indentation consistently in osx-token-store.ts

- src/commands/codepush/lib/hash-utils.ts
- src/commands/codepush/lib/update-contents-tasks/sign.ts
- src/commands/codepush/lib/update-contents-tasks/zip.ts
> Fixed isDirectory() method.

- contributing.md
Updated:
- instructions for submitting a PR
> Included instructions for submitting a PR

- src/commands/test/lib/run-tests-command.ts
- src/commands/test/lib/uitest-preparer.ts
- src/commands/test/prepare/uitest.ts
- src/commands/test/run/uitest.ts
Fix fixture chunking: The option is now included when starting the test run.
> pass option all the way to the backend

- src/util/portal/portal-helper.ts
- test/commands/test/util/portal-helper-test.ts
> Add url encoding

- src/commands/codepush/lib/release-command-skeleton.ts
PR contains fix for https://github.com/Microsoft/appcenter-cli/issues/469
**Solution**: added the ability to get access token from environment variable
> Fixed cli access token issue

- test/commands/test/generate/appium-test.ts
- test/commands/test/generate/uitest-test.ts
- Removed excessive step from appium tests.
- Changed test output dir for generate uitest command.
> Cleanup tests.

- src/commands/setup-autocomplete.ts
Added `result` to finish command if autocomplete was configured before.
> Added result to finish command if autocomplete was configured before.

- package-lock.json
- package.json
- Adds additional info(Metadata and Metrics) for codepush deployment list (https://github.com/Microsoft/appcenter-cli/pull/492)
- Adds additional info(Metadata and Metrics) for codepush deployment history (https://github.com/Microsoft/appcenter-cli/pull/488)
> Release 1.1.5

- package-lock.json
- package.json
> Release 1.1.7

- package-lock.json
- package.json
- Fixes `event-stream` module to 3.3.4 due to vulnerability
- Adds ability to set app context for Test Wizard
> Release 1.1.8

- src/util/profile/environments.ts
Internal change for the App Center team.
> Updated INT portal URLs

- package-lock.json
- package.json
- Internal changes to aid developers, no new features or fixes.
> Release 1.1.9

- README.md
There was no reference to our support options.
> Added support content

- package-lock.json
- package.json
Temporary fix for this issue: https://github.com/mafintosh/pumpify/issues/9
> Pins @types/duplexify to 3.5.0 until type issue is resolved

- package-lock.json
- package.json
- Adds support content to README
- Removes `event-stream` dependency
- Adds option to specify the file name when downloading a build
- Adds AAR as supported package extension for build downloads
- Adds key to add code-push deployment output
- Fix generating sourceMaps for react-native CodePush
> Release 1.1.10

- package-lock.json
- package.json
- Fixes cli running on Windows (broken by regression on v1.1.10)
> Release 1.1.11

- README.md
- package-lock.json
- src/commands/codepush/lib/electron-utils.ts
- src/commands/codepush/release-electron.ts
- test/commands/codepush/codepush-release-test.ts
Add support for release-electron to codepush command.
Also, fixed a npm audit issue.
> Add support for release-electron to codepush command

- package-lock.json
- package.json
- Updates Swagger files and autogenerated service code to latest version
> Release 1.1.13

- src/commands/distribute/releases/show.ts
> Add enabled status to show release command

- src/commands/distribute/lib/distribute-util.ts
- src/commands/distribute/release.ts
- src/commands/distribute/releases/add-destination.ts
As discussed in #557, this pull request moves the two commonly used functions into their own util module.
> Consolidate common distribution code

- src/commands/distribute/releases/show.ts
Changing array length check to be more than zero instead of one
> [Bug] Changing array length check to be more than zero instead of one

- .gitignore
- src/commands/test/lib/templates/uitest/android/AppCenter.UITest.Android/AppCenter.UITest.Android.csproj
- src/commands/test/lib/templates/uitest/android/AppCenter.UITest.Android/Tests.cs
- src/commands/test/lib/templates/uitest/android/AppCenter.UITest.Android/packages.config
- src/commands/test/lib/templates/uitest/ios/AppCenter.UITest.iOS/AppCenter.UITest.iOS.csproj
- src/commands/test/lib/templates/uitest/ios/AppCenter.UITest.iOS/Tests.cs
- src/commands/test/lib/templates/uitest/ios/AppCenter.UITest.iOS/packages.config
- src/commands/test/lib/uitest-preparer.ts
- Update exe name when using locally built test-cloud.exe
- Use UITest 3.0.0 and NUnit 3.11.0
> Support UITest 3 & NUnit 3

- package-lock.json
- package.json
- Updates Xamarin.UITest launch test projects to use 3.0.0
> Release 1.0.17

- package-lock.json
- package.json
- Changes unzip to use the better maintained unzipped
- Fixes issues with the way zip file streams were being handled
> Release v1.1.18

- README.md
- package-lock.json
- package.json
- Adds command for uploading android Mappings [#594](https://github.com/microsoft/appcenter-cli/pull/594)
> Release 1.1.19

- package-lock.json
- package.json
- Add warning for poor target-binary-version in codepush
- Bump lodash dependency version
> Release 1.1.20

- src/commands/test/lib/templates/appium/android/pom.xml
- src/commands/test/lib/templates/appium/ios/pom.xml
https://appcenter.ms/orgs/App-Center-Test-Cloud/apps/Palisade-iOS/test/runs/b4a1873a-f5d8-4d17-b2c0-8e5d876708fe
https://appcenter.ms/orgs/App-Center-Test-Cloud/apps/Palisade-Android/test/runs/984ac3cd-1723-4b6a-9c5a-d1a491ec47bd
> Updates appium launch test projects to latest appium client

- package-lock.json
- package.json
-  Fixes UITest XML merge issue on large XML files
> Release 1.2.1

- .vscode/launch.json
- test/commands/distribute/release/release-test.ts
1. added tests for code in #626 (`--build-version` parameter in `distribute release` command)
2. updated `launch.json` file configuration
> Build version parameter tests

- package-lock.json
- package.json
- Add `--build-version` parameter to the `distribute release` command.
> Update version to 2.1.0

- package-lock.json
- package.json
- Adds `.appxsym` file support for UWP Apps in `crashes` command
> Release 2.1.2

- azure-pipelines.yml
Add optional variable to ignore some directories for Component Governance. Set up to ignore templates using a variable set in AzDO.
> Update azure-pipelines.yml to ignore false alerts

- src/commands/distribute/release.ts
- test/commands/distribute/release/release-test.ts
This adds support for macOS releases of type `.dmg` and `.pkg`, as they require explicit setting of both `--build-version` and `--build-number`.
This will address #670
> Add support for macOS .pkg & .dmg files

- KNOWN_ISSUES.md
- README.md
This can be expanded in the future when we have issues that can be worked around but fixing them in code would be too hard or impossible.
> Add KNOWN_ISSUES.md

- src/commands/test/lib/state-checker.ts
Retry test run status checks
This will allow us to recover from transient network issues
> Retry test run status checks

- src/commands/apps/create.ts
Improve documentation to add current supported os and platforms.
> Add all supported os and platforms in the app create help

- src/commands/test/lib/templates/uitest/android/AppCenter.UITest.Android/AppCenter.UITest.Android.csproj
- src/commands/test/lib/templates/uitest/android/AppCenter.UITest.Android/packages.config
- src/commands/test/lib/templates/uitest/ios/AppCenter.UITest.iOS/AppCenter.UITest.iOS.csproj
- src/commands/test/lib/templates/uitest/ios/AppCenter.UITest.iOS/packages.config
- test/commands/test/generate/uitest-test.ts
> Use UITest 3.0.4 in launch tests

- src/commands/test/lib/templates/uitest/android/AppCenter.UITest.Android/AppCenter.UITest.Android.csproj
- src/commands/test/lib/templates/uitest/android/AppCenter.UITest.Android/packages.config
- src/commands/test/lib/templates/uitest/ios/AppCenter.UITest.iOS/AppCenter.UITest.iOS.csproj
- src/commands/test/lib/templates/uitest/ios/AppCenter.UITest.iOS/packages.config
- test/commands/test/generate/uitest-test.ts
This simply updates the version of UITest used by the launch tests.
> Launch tests use UITest 3.0.5

- package-lock.json
- package.json
This updates Xamarin.UITest, which solves issues with an invalid certificate.
> Version 2.3.3 with updated Xamarin.UITest

- src/commands/distribute/lib/distribute-util.ts
- src/commands/distribute/release.ts
- test/commands/distribute/release/release-test.ts
- test/functional/commands/distribute/Release.Tests.ps1
> Adding --mandatory to distribute-release

- package-lock.json
- package.json
Changes:
- Codepush fix for XCode 11
- Command line help fixes
- Ran `npm audit fix` to fix vulnerable dependencies
- Add functional test
> Release 2.3.4 with codepush fix

- package-lock.json
- package.json
Create appcenter-cli version 2.4.1
> Cli Version 2.4.1

- src/commands/telemetry/off.ts
- src/commands/telemetry/on.ts
- src/util/commandline/command.ts
> Disable telemetry and the telemetry question on the `telemetry` command.

- package-lock.json
- package.json
Minor version update for new (minor) features and bug fixes.
> Version to 2.5.0

- src/commands/distribute/releases/edit.ts
> Fix copy paste debug typo

- package-lock.json
- package.json
Dependency updates.
- @typescript-eslint/eslint-plugin from 2.31.0 to 2.34.0.
- @typescript-eslint/parser from 2.31.0 to 2.34.0.
- date-fns from 2.12.0 to 2.14.0.
- typescript from 3.8.3 to 3.9.3.
> Version number to 2.5.3

- package-lock.json
Fix package-lock.json file, that was changed during feature development.
> Fix package-lock.json file.

- package-lock.json
- package.json
- src/commands/distribute/lib/mc-fus-uploader/mc-fus-mime-types.ts
- src/commands/distribute/lib/mc-fus-uploader/mc-fus-uploader.ts
- src/commands/distribute/release.ts
- tsconfig.json
- Revert tsconfig
- Remove unused methods inside release command 
- Fix typescript error in mc-fus-uploader library
[AB#80767](https://msmobilecenter.visualstudio.com/Mobile-Center/_boards/board/t/IvanM-Team/Backlog%20Items/?workitem=80767)
> Revert tsconfig

- package.json
- src/commands/distribute/lib/mc-fus-uploader/mc-fus-uploader.ts
- test/commands/distribute/release/mockWorker.js
- test/commands/distribute/release/release-test.ts
This PR modifies all the unit tests with regards to the feature.
> Fix all the unit tests

- src/commands/distribute/lib/mc-fus-uploader/mc-fus-uploader-types.ts
- src/commands/distribute/lib/mc-fus-uploader/mc-fus-uploader.ts
- src/commands/distribute/lib/mc-fus-uploader/readme.md
- src/commands/distribute/release.ts
- test/commands/distribute/lib/mc-fus-uploader-test.ts
Address feedback from https://github.com/microsoft/appcenter-cli/pull/909
> Address fus-library feedback

- src/commands/distribute/release.ts
Tests should pass regardless of the login
> Rework endpoint

- README.md
- package-lock.json
- package.json
Increasing minor version number for new command and release upload speed improvement.
> Version to 2.6.0. Update README with new command.

- SECURITY.md
- contributing.md
- package.json
- src/commands/codepush/release-electron.ts
- src/commands/codepush/release-react.ts
- src/util/apis/generated/operations/errors.js
- src/util/apis/generated/operations/index.d.ts
- swagger/bifrost.swagger.before.json
- swagger/bifrost.swagger.json
A few typo and capitalization fixes
> Fix typos and capitalization

- package-lock.json
- package.json
Description of the release will be:
Minor fixes and dependency updates:
- Stop waiting for a release to load if an error occurs.
- Fix typos, thanks @friederbluemle.
- Run functional tests more reliably in PR pipeline.
- Update inquirer from 7.2.0 to 7.3.0.
- Update nock from 12.0.3 to 13.0.2.
- Update through2 from 3.0.1 to 4.0.2.
- Update typescript from 3.9.5 to 3.9.6.
- Update some @types packages.
> Version number to 2.6.1

- src/commands/distribute/release.ts
> Fix release upload with token as env var

- package-lock.json
- package.json
There are internal changes, a bug fix and dependency updates. Hence a patch version update.
> Version number to 2.6.4

- package-lock.json
- package.json
Release will contain a revert of part of the previous patch release.
> Version number to 2.6.5

- package-lock.json
- package.json
Dependency updates and fix to handle dependency change.
> Version number to 2.6.6

- appcenter-file-upload-client-node/package-lock.json
- appcenter-file-upload-client-node/package.json
> appcenter-file-upload-client-node version to 1.1.1

- package-lock.json
- package.json
> Version to 2.7.0 with latest appcenter-file-upload-client-node

- appcenter-file-upload-client-node/package-lock.json
- appcenter-file-upload-client-node/package.json
> appcenter-file-upload-client-node version to 1.1.2

- package-lock.json
- package.json
Dependency updates and actually uptaking the thing that should have been in 2.7.0
> Version to 2.7.1

- package-lock.json
- package.json
> Version to 2.7.3

- package-lock.json
- package.json
Dependency updates and a few bug fixes.
Difference https://github.com/microsoft/appcenter-cli/compare/v2.7.3...bdfea85c80081a172798bc98f4afd30c14bf8932
Bug fixes:
[[Distribution] Do not call abortReleaseUpload API when uploading file failed](https://github.com/microsoft/appcenter-cli/pull/1192)
[[CodePush] Add limit for request](https://github.com/microsoft/appcenter-cli/pull/1215)
[[CodePush] Fix json output](https://github.com/microsoft/appcenter-cli/pull/1244)
> Version number to 2.7.4

- appcenter-file-upload-client-node/src/ac-fus-uploader.ts
Asset ID info added to log properties - initializeUpload method
> asset ID info added to log properties

- src/commands/distribute/release.ts
As per #1213, this PR is to improve help output of commands
> Improve group and release-notes commands descriptions

- package-lock.json
- package.json
Improvements, dependency updates, and several bug fixes.
Difference https://github.com/microsoft/appcenter-cli/compare/v2.7.4...ea287a15395c050c9d16e9f9229faef0bd415706
Improvements:
[[Distribution] Flexible distribution: The CLI tool now supports distributing a release to multiple distribution groups](https://github.com/microsoft/appcenter-cli/pull/1253)
Minor improvements:
[[Distribution] Improve group and release-notes commands descriptions](https://github.com/microsoft/appcenter-cli/pull/1318)
[[Test] Update test chunking failed error messsage](https://github.com/microsoft/appcenter-cli/pull/1281)
Bug fixes:
[[CodePush] Fix release issue](https://github.com/microsoft/appcenter-cli/pull/1252)
[[CodePush] Cordova: Enhance error handling for config.xml …
> Version number to 2.8.0

- package-lock.json
- package.json
Dependency updates.
Difference: https://github.com/microsoft/appcenter-cli/compare/v2.8.0...29308187d95f8fd1325133de53b3e88fbf283c16
> Version number to 2.8.1

- appcenter-file-upload-client-node/package-lock.json
- appcenter-file-upload-client-node/package.json
- appcenter-file-upload-client-node/tsconfig.json
[AB#85977](https://msmobilecenter.visualstudio.com/Mobile-Center/_boards/board/t/Ivan-Team/Backlog%20Items/?workitem=85977)
> Update proxy agent dependency

- src/commands/analytics/audience.ts
This PR adds verification before performing loadActiveUsersStatistics AB#86189
> Add verification before loadActiveUsersStatistics

- package-lock.json
- package.json
- src/commands/test/lib/junit-xml-util.ts
- src/commands/test/lib/nunit-xml-util.ts
- src/commands/test/lib/xml-util.ts
- test/commands/test/util/junit-xml-util-test.ts
- test/commands/test/util/nunit-xml-util-test.ts
> Update xmldom dependency

- appcenter-file-upload-client-node/src/ac-fus-uploader.ts
This PR is improving logic of error messaging in cases if user have VPN of Firewall.
[AB#1644](https://github.com/microsoft/appcenter-cli/issues/1644/)
> [appcenter-file-upload-client-node] More informative error message for distribute release

- package-lock.json
- package.json
- src/commands/distribute/release.ts
Remove blocker code for uploading `.aab` files.
Note: This PR should be merged after:
1. Merge https://github.com/microsoft/appcenter-cli/pull/1688
2. Publish a new version of `appcenter-file-upload-client-node` package.
3. Bump to new version of `appcenter-file-upload-client-node` package in this PR.
> Remove blocker for uploading aab

- src/commands/test/lib/templates/appium/ios/src/test/java/com/azure/mobile/app/test/LaunchTest.java
Add XCUITest capability to the test cloud appium template
> Add XCUITest capability for appium

- package-lock.json
- package.json
This PR fixes the following vulnerability issues:
- [json-schema is vulnerable to Prototype Pollution ](https://github.com/advisories/GHSA-896r-f27r-55mw) 
- [Inefficient Regular Expression Complexity in validator.js](https://github.com/advisories/GHSA-qgmg-gppg-76g5 )
> Bump azure-storage to 2.10.6

- package-lock.json
- package.json
[AB#89916](https://msmobilecenter.visualstudio.com/Mobile-Center/_boards/board/t/Mobile%20SDK/Backlog%20Items/?workitem=89916)
Issue https://github.com/microsoft/appcenter-cli/issues/1785
> Fix-zalgo-issue-in-cli-table3

- src/commands/codepush/patch.ts
Fix Cannot patch latest release when only setting --disabled false issue 
Related issue: [1820](https://github.com/microsoft/appcenter-cli/issues/1820/)
> Update condition for isDisabled and isMandatory properties

- package-lock.json
[AB#91928](https://dev.azure.com/msmobilecenter/Mobile-Center/_workitems/edit/91928)
> Fix simple-plist vulnerability

- package-lock.json
- package.json
[AB#92064](https://dev.azure.com/msmobilecenter/Mobile-Center/_workitems/edit/92064)
> Fix malware in es5-ext package

- package-lock.json
- package.json
[AB#92206](https://dev.azure.com/msmobilecenter/Mobile-Center/_workitems/edit/92206)
> Version number to 2.10.10

- README.md
[AB#1904](https://github.com/microsoft/appcenter-cli/issues/1904/)
> Fix prerequisites for UI test

- bin/appcenter.js
- package-lock.json
- package.json
[AB#93788](https://dev.azure.com/msmobilecenter/Mobile-Center/_workitems/edit/93788)
> Bump update-notifier to 6.0.2 and adapt to ESM

- src/commands/codepush/lib/react-native-utils.ts
[AB#91812](https://msmobilecenter.visualstudio.com/Mobile-Center/_boards/board/t/TestCloud%20Mobile/Backlog%20Items/?workitem=91812)
> Fix hermes detection for iOS

- package-lock.json
- package.json
[AB#94199](https://msmobilecenter.visualstudio.com/Mobile-Center/_boards/board/t/TestCloud%20Mobile/Backlog%20Items/?workitem=94199)
> Version number to 2.11.0

- package-lock.json
- package.json
Fix [CG Alert 94950](https://dev.azure.com/mseng/PipelineTools/_componentGovernance/184?alertId=94950)
AB#[98870](https://msmobilecenter.visualstudio.com/Mobile-Center/_boards/board/t/SDK/Backlog%20Items/?workitem=98870)
> Fix CVE-2022-37616 in @xmldom/xmldom 0.7.5. Severity: Critical

- src/commands/codepush/lib/codepush-release-command-base.ts
- src/commands/codepush/patch.ts
- src/commands/codepush/promote.ts
- test/commands/codepush/release-test.ts
Update rollout error message
Looks like rollout is supposed to be a value between 1 & 100 but the error message is a little misleading. Fix the message and the grammer.
> Update rollout error message

- src/commands/test/lib/templates/appium/android/pom.xml
- src/commands/test/lib/templates/appium/ios/pom.xml
AB#[100495](https://dev.azure.com/msmobilecenter/Mobile-Center/_workitems/edit/100495)
> Fix spring extension vulnerability

- azure-pipelines.yml
This reverts commit 7b7e459212843ab9d16f41169cea771135b16467.
> Revert "Run functional tests only if variable is set"

- package-lock.json
- package.json
This release includes:
- https://github.com/microsoft/appcenter-cli/pull/2341
- https://github.com/microsoft/appcenter-cli/pull/2348
> Version 2.13.9

- package-lock.json
- package.json
- https://github.com/microsoft/appcenter-cli/pull/2387
> Version 2.13.10

- appcenter-cli-1ES.yml
- test/util/token-store/osx-keychain-parser-test.ts
Migrating Pipelines to 1ES Template. 
[AB#104414](https://dev.azure.com/msmobilecenter/Mobile-Center/_boards/board/t/Mobile%20SDK%20team/Backlog%20Items/?workitem=104414)
> [Pipelines] Migrate to 1ES pipeline. 

- .azurepipelines/appcenter-cli-1ES.yml
This PR adds APIScan to the CI pipeline.
[AB#104343](https://dev.azure.com/msmobilecenter/Mobile-Center/_workitems/edit/104343)
[APIScan Build](https://dev.azure.com/msmobilecenter/SDK/_build/results?buildId=1515810&view=results)
> [CI] Add APIScan

- appcenter-file-upload-client-node/package-lock.json
Fixes vulnerabilities for upload-client-node :
ip - https://github.com/advisories/GHSA-78xj-cgh5-2h22
[Build](https://dev.azure.com/msmobilecenter/SDK/_build/results?buildId=1531328&view=results)
> Fix vulnerabilities

- appcenter-file-upload-client-node/package-lock.json
- appcenter-file-upload-client-node/package.json
Update appcenter-file-upload-client-node version
> Update appcenter-file-upload-client-node version to 1.2.12

- src/commands/test/lib/templates/appium/android/pom.xml
- src/commands/test/lib/templates/appium/ios/pom.xml
Fix vulnerability [CVE-2022-22968](https://spring.io/security/cve-2022-22968)
[Build](https://dev.azure.com/msmobilecenter/SDK/_build/results?buildId=1531888&view=results)
> Fix vulnerability

- src/util/profile/environments.ts
Updated integration environment url as the old one was no longer working.
[AB#107324](https://dev.azure.com/msmobilecenter/Mobile-Center/_boards/board/t/Mobile%20SDK%20team/Backlog%20Items/?workitem=107324)
[Build](https://dev.azure.com/msmobilecenter/SDK/_build/results?buildId=1545586&view=results)
> Update integration environment url

- .azurepipelines/appcenter-cli-1ES.yml
Bump AzureKeyVault task
[Build](https://dev.azure.com/msmobilecenter/SDK/_build/results?buildId=1546110&view=results)
> [CI] Update AzureKeyVault task version

- package-lock.json
- package.json
- https://github.com/microsoft/appcenter-cli/pull/2542
- https://github.com/microsoft/appcenter-cli/pull/2497
- https://github.com/microsoft/appcenter-cli/pull/2544
- https://github.com/microsoft/appcenter-cli/pull/2548
- https://github.com/microsoft/appcenter-cli/pull/2543
- https://github.com/microsoft/appcenter-cli/pull/2550
- https://github.com/microsoft/appcenter-cli/pull/2551
[#AB107835
](https://dev.azure.com/msmobilecenter/Mobile-Center/_workitems/edit/107835)
> Version 3.0.2
